### PR TITLE
Sprays Importer/Gallery + fixed empty spray + NeoUI Texture/Image button + stb libraries + server-side disable spray

### LINKED ISSUE #602: [FEATURE] Root NeoUI - Sprays
### Description

Subtask of the root menu/NeoUI - Add support for creating custom sprays

### Proposed Solution

* Add ability to create custom sprays through the NeoUI settings page

### Alternatives Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nullsystem**
## Description

* Added in `sv_neo_spraydisable` so server-side can disable it (also enabled if competitve mode enabled)

TODO:
- [x] Try out exporting DXT5 instead of DXT1. Seems DXT5 works for spray and can deal with transparency well
- [x] Change importer behavior from always the same spray.vtf to also applying by filename's basename + .vtf/.vmt

* Spray now put into the NeoUI settings menu
    * Import button to import sprays
    * Gallery button to pick a spray from current already available set
    * An image on the left to show the current spray
    * Outputs VTF 7.4 DXT1/DXT5 format and 2 VMT files, one for UI and one general
* Spray fix - fixed for local player's spray not showing up properly
    * The issue affected both default and custom sprays
* Function to generate VTF 7.4 + DXT1/DXT5 image 
    * This is partially because Source SDK's RGBA8888 to DXT conversion was broken, so a "custom" function is done instead
    * It just lays out the VTF headers, the 4 mipmaps from smallest to largest, then DXT1 or DXT5 block per mipmap images
    * It will use DXT5 if there's any transparency/usage of alpha values, otherwise DXT1 will be use if no alpha is needed due to the smaller size
* NeoUI image/texture support - New `Texture` and `ButtonTexture`
    * The texture can be initialized from vmt texture, vtf texture direct, and general images like PNG or JPG
    * Makes sure image aspect ratio and fit is correct within the given bounds
* NeoUI scrolling fixes
    * Fixed to use y-partition instead of widget indexes
    * Scrollbar is now determined by X-margin
* New libraries usages:
    * All from: https://github.com/nothings/stb
    * `stb_image.h` for image reading (PNG, JPG) (used for both spray importer and NeoUI image support)
    * `stb_image_resize2.h` for image resizing (used for spray importer)
    * `stb_dxt.h` for outputting DXT1 blocks (used for spray importer)

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

- fixes #602 

## Screenshot

2025-02-17T213909_screen

### CODE REVIEW

**Review by brysondev — APPROVED** [review]
LGTM

**Comment by AdamTadeusz** [comment]
what have we decided in terms of including the new library, does it pose a security threat?

**Comment by Masterkatze** [comment]
> what have we decided in terms of including the new library, does it pose a security threat?

I don't think so, since it's used only on client side.

File: mp/src/game/client/neo/ui/neo_root_settings.cpp [hunk 1]
```diff
@@ -645,14 +646,62 @@ void NeoSettings_General(NeoSettings *ns)
...
 	NeoUI::RingBoxBool(L"Auto streamer mode (requires restart)", &pGeneral->bAutoDetectOBS);
 	NeoUI::Label(L"OBS detection", g_bOBSDetected ? L"OBS detected on startup" : L"Not detected on startup");
-	NeoUI::RingBoxBool(L"Show rangefinder", &pGeneral->bEnableRangeFinder);
+
+	NeoUI::Label(L"DOWNLOADING", CENTER_OPT);
+	NeoUI::RingBoxBool(L"Show player spray", &pGeneral->bShowPlayerSprays);
+	NeoUI::RingBox(L"Download filter", DLFILTER_LABELS, ARRAYSIZE(DLFILTER_LABELS), &pGeneral->iDlFilter);
+
+	NeoUI::Label(L"SPRAY", CENTER_OPT);
+	if (NeoUI::Button(L"Current spray:", L"Import spray").bPressed)
```
Comment (Masterkatze) [inline mp/src/game/client/neo/ui/neo_root_settings.cpp:665]: `L"Current spray"`

**Comment by Masterkatze** [comment]
1. Missing texture at the first start:
1_missing_texture

2. I think the settings menu could be improved - move the controls/values to the right column:
2_settings

File: mp/src/game/client/neo/ui/neo_root_settings.cpp (hunk 1 above)
Comment (AdamTadeusz) [reply mp/src/game/client/neo/ui/neo_root_settings.cpp:665]: In the crosshair section, the crosshair at the top of the menu is implied to be the current crosshair, without any text labeling it as the current crosshair. Perhaps we should follow this trend here and get rid of the "Current spray:" label

File: mp/src/game/client/neo/ui/neo_root.cpp [hunk 2]
```diff
@@ -1200,6 +1203,99 @@ void CNeoRoot::MainLoopMapList(const MainLoopParam param)
...
+	const int iNormTall = g_uiCtx.iRowTall;
+	const int iCellTall = iNormTall * 4;
+
+	const int iTallTotal = iNormTall * (g_iRowsInScreen + 2);
+	g_uiCtx.dPanel.wide = g_iRootSubPanelWide;
+	g_uiCtx.dPanel.x = (param.wide / 2) - (g_iRootSubPanelWide / 2);
+	g_uiCtx.dPanel.y = (param.tall / 2) - (iTallTotal / 2);
+	g_uiCtx.dPanel.tall = iNormTall * (g_iRowsInScreen + 1);
+	g_uiCtx.bgColor = COLOR_NEOPANELFRAMEBG;
+	NeoUI::BeginContext(&g_uiCtx, param.eMode, L"Pick spray", "CtxSprayPicker");
```
Comment (AdamTadeusz) [inline mp/src/game/client/neo/ui/neo_root.cpp:1253]: maybe "Pick a Spray"? I don't think we're short on space here

**Review by AdamTadeusz — DISMISSED** [review]

**Comment by AdamTadeusz** [comment]
@nullsystem also conflicts

**Comment by brysondev** [comment]
Waiting on nits before approving

**Review by brysondev — DISMISSED** [review]
Nuh uh

**Review by brysondev — DISMISSED** [review]

**Review by brysondev — APPROVED** [review]
Oh so we are merging this

**Comment by nullsystem** [comment]
Added in `neo_sv_spraydisable` so server-side can disable it (also enabled if competitve mode enabled)

File: src/game/client/c_te_playerdecal.cpp [hunk 3]
```diff
@@ -28,6 +28,10 @@ static ConVar cl_spraydisable( "cl_spraydisable", "1", FCVAR_CLIENTDLL | FCVAR_A
 static ConVar cl_spraydisable( "cl_spraydisable", "0", FCVAR_CLIENTDLL | FCVAR_ARCHIVE, "Disable player sprays." );
 #endif
 
+#ifdef NEO
+extern ConVar neo_sv_spraydisable;
```
Comment (brysondev) [inline src/game/client/c_te_playerdecal.cpp:32]: Can we make it sv_neo?

File: src/game/shared/neo/neo_gamerules.cpp [hunk 4]
```diff
@@ -39,6 +39,8 @@ ConVar mp_neo_latespawn_max_time("mp_neo_latespawn_max_time", "15", FCVAR_REPLIC
 ConVar sv_neo_wep_dmg_modifier("sv_neo_wep_dmg_modifier", "1", FCVAR_REPLICATED, "Temp global weapon damage modifier.", true, 0.0, true, 100.0);
 ConVar neo_sv_player_restore("neo_sv_player_restore", "1", FCVAR_REPLICATED, "If enabled, the server will save players XP and deaths per match session and restore them if they reconnect.", true, 0.0f, true, 1.0f);
 
+ConVar neo_sv_spraydisable("neo_sv_spraydisable", "0", FCVAR_REPLICATED, "If enabled, disables the players ability to spray.", true, 0.0f, true, 1.0f);
```
Comment (brysondev) [inline src/game/shared/neo/neo_gamerules.cpp:42]: ditto

**Review by brysondev — DISMISSED** [review]
@Agiel have we decided on what we want to use?

**Review by brysondev — DISMISSED** [review]

**Review by brysondev — DISMISSED** [review]

**Review by brysondev — APPROVED** [review]

**Review by Masterkatze — APPROVED** [review]
LGTM
