### PR TITLE
Fix 1st person spectator not seeing crosshair and viewmodel offset on aim

### LINKED ISSUE #393: [BUG] 1st person spectator does not see crosshair and viewmodel ADS offset
### Build Info

20240623_bd6db75 (nullsystem:GH-389_neoFovFixRelay)

### Description

1st person spectator is missing a crosshair/scoped crosshair, and viewmodel ADS offset when the player its spectating is doing ADS.

Related PR #390 which deals with spectator FOV, this should be done after that one.

### To Reproduce

1. Requires two clients on a running server
2. One client spectate, the other play as Jinrai/NSF
3. Server controlling player use `sv_cheats 1`, then
 `give weapon_srs` for SRS to test scoped weapon
4. Spectating player spectate the player in 1st person mode
5. Playing player try ADS with a non-scoped weapon EX: srm, and scoped weapon EX: srs
6. Spectating player look at how the ADS looks while it ADS/un-ADS

### Expected behavior

Crosshair/scoped crosshair and viewmodel is offset to ADS values is viewed from the spectator POV.

### Actual behavior

No crosshair or scoped crosshair, and viewmodel stays in the normal position from the spectator POV.

### Operating System

- [x] Windows
- [X] Linux

### Version/Distro

Arch Linux

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

Scoped weapon (SRS) aiming in scoped sight from spectator POV:
2024-06-23T132320_screen
Non-scoped weapon (milso) aiming in ADS from spectator POV:
2024-06-23T132258_screen

### PR DESCRIPTION
**Pull request by nullsystem**
## Description

1st person spectator now have crosshair/scoped crosshair, and viewmodel ADS offset when the player its spectating is doing ADS.

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

- fixes #393
- related #390

### CODE REVIEW

File: mp/src/game/client/c_baseplayer.cpp [hunk 1]
```diff
@@ -1782,6 +1782,20 @@ void C_BasePlayer::CalcInEyeCamView(Vector& eyeOrigin, QAngle& eyeAngles, float&
 	}
 
 	engine->SetViewAngles( eyeAngles );
+
+#ifdef NEO
+	if (auto *pTargetNeoPlayer = dynamic_cast<CNEO_Player *>(target))
```
Comment (Rainyan) [inline mp/src/game/client/c_baseplayer.cpp:1787]: Can be `static_cast` as per above assertions.

File: mp/src/game/shared/baseplayer_shared.cpp [hunk 2]
```diff
@@ -1726,6 +1726,9 @@ void CBasePlayer::CalcVehicleView(
 void CBasePlayer::CalcObserverView( Vector& eyeOrigin, QAngle& eyeAngles, float& fov )
 {
 #if defined( CLIENT_DLL )
+#ifdef NEO
+	m_Local.m_iHideHUD &= ~HIDEHUD_CROSSHAIR;
+#endif
```
Comment (Rainyan) [inline mp/src/game/shared/baseplayer_shared.cpp:1731]: This has the side effect of displaying the crosshair to spectators upon joining  the server:



Do we need to clear this bit here for some purpose?

**Review by Rainyan — CHANGES_REQUESTED** [review]

File: mp/src/game/shared/baseplayer_shared.cpp (hunk 2 above)
Comment (nullsystem) [reply mp/src/game/shared/baseplayer_shared.cpp:1731]: Whoops that's a screw up, should be the otherway round.

**Review by Rainyan — APPROVED** [review]

**Review by AdamTadeusz — APPROVED** [review]
