### PR TITLE
Players should bleed when shot by other players

### LINKED ISSUE #1460: Teammates should bleed
### Build Info

20251026_3a89b3d

### Description

There's no blood splat when shooting a teammate, even though friendly fire is enabled.

### To Reproduce

1. Position a team mate near a wall
2. Shoot them

### Expected behavior

A blood splat appears on the wall or floor

### Actual behavior

No splat (although a decal does appear on the player model).

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

Previous PR #1605

## Toolchain

- Windows MSVC VS2022

## Linked Issues

- fixes #1460

### CODE REVIEW

File: src/game/shared/shareddefs.h [hunk 1]
```diff
@@ -793,10 +793,13 @@ struct FireBulletsInfo_t
 		m_vecDirShooting.Init( VEC_T_NAN, VEC_T_NAN, VEC_T_NAN );
 #endif
 		m_bPrimaryAttack = true;
+#ifdef NEO
+		m_nbDoServerEffects = true;
```
Comment (DESTROYGIRL) [inline src/game/shared/shareddefs.h]: Why m_nb

File: src/game/shared/baseentity_shared.cpp [hunk 2]
```diff
@@ -2162,16 +2168,14 @@ void CBaseEntity::FireBullets( const FireBulletsInfo_t &info )
...
 
+#ifndef NEO
 #if defined( HL2MP ) && defined( GAME_DLL )
 	if ( bDoServerEffects == false )
 	{
-#ifdef NEO
-		TE_HL2MPFireBullets(entindex(), tr.startpos, info.m_vecDirShooting, info.m_iAmmoType, iEffectSeed, info.m_iShots, info.m_vecSpread, bDoTracers, bDoImpacts);
-#else
 		TE_HL2MPFireBullets( entindex(), tr.startpos, info.m_vecDirShooting, info.m_iAmmoType, iEffectSeed, info.m_iShots, info.m_vecSpread.x, bDoTracers, bDoImpacts );
-#endif
```
Comment (Rainyan) [inline src/game/shared/baseentity_shared.cpp:2172]: Could revert these changes to `TE_HL2MPFireBullets` and related stuff regarding `m_vecSpread` at some point if we don't use it anymore. But I guess doesn't have to be this PR.

**Review by Rainyan — APPROVED** [review]

File: src/game/shared/baseentity_shared.cpp (hunk 2 above)
Comment (AdamTadeusz) [reply src/game/shared/baseentity_shared.cpp:2172]: https://github.com/NeotokyoRebuild/neo/issues/1763
