### PR TITLE
Team/Class/Loadout menu opening correctly

### LINKED ISSUE #378: [BUG] Incorrect team menu flow when reversing
After choosing a team, reverting that decision makes you skip class and loadout selection entirely for that menu flow.

### Steps to reproduce
* Join a server
* Dismiss MOTD if any
* (The team selection menu appears)
* Join Jinrai or NSF
* (The class selection menu appears)
* Press `<< CHANGE TEAM` to revert your team selection
* (The team selection menu appears)
* Join Jinrai or NSF

### What happens
* No menu appears.

### What should happen
* The class selection menu appears.

### LINKED ISSUE #385: [BUG] Spectators shown the class menu on round start
### Build Info

20240620_f670f82 (master-f670f828687a22886a4d6b89fc09fcaea9b23e70)

### Description

Players spectator the game (not in Jinrai or NSF) are shown the class menu on the start of each round. This is despite spectators aren't playing and don't have class or weapon selection.

### To Reproduce

1. Open game -> Create Server -> Start
2. Pick spectator
3. Go to console and create bots to start a match:
   ```
   sv_cheats 1
   mp_neo_warmup_round_time 0
   bot_add;bot_add;bot_add;bot_add;
   ```
4. Wait till round starts

### Expected behavior

There's no menu automatically shown for the spectator on round start

### Actual behavior

There's a class menu automatically shown for the spectator on round start

### Operating System

- [X] Windows
- [X] Linux

### Version/Distro

Arch Linux; Windows 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

The class menu automatically pops up even as a separator:
2024-06-20T211555_screen

### PR DESCRIPTION
**Pull request by VantoNortim**
## Description
Cleanup menu openings
Do not open class menu on round start for spectators

## Toolchain
- Windows MSVC VS2022

## Linked Issues
- fixes #385
- fixes #378

### CODE REVIEW

File: mp/src/game/client/clientmode_shared.cpp [hunk 1]
```diff
@@ -1116,6 +1116,12 @@ void ClientModeShared::FireGameEvent( IGameEvent *event )
 		{
 			// that's me
 			pPlayer->TeamChange( team );
+
+			auto neoPlayer = dynamic_cast<C_NEO_Player*>(pPlayer);
+			if(neoPlayer)
+			{
+				engine->ClientCmd("classmenu");
+			}
```
Comment (Rainyan) [inline mp/src/game/client/clientmode_shared.cpp:1124]: Wrap our code in `#ifdef NEO`...`#endif` inside Valve blocks.

Also, I don't think you need to do this cast - if we've got a valid player pointer, it should be a safe assertion that it is always a valid `C_NEO_Player*`. Although you could `Assert(dynamic_cast<C_NEO_Player*>(pPlayer))` as a sanity check if you want to, since the assertion would be optimized away from a release build.

But I think since the Valve code at line 1118 above this is calling `pPlayer->TeamChange` here anyway, this might fit better as `virtual void TeamChange(int iNewTeam) override` for the client side `C_NEO_Player` class.

**Review by Rainyan — CHANGES_REQUESTED** [review]

**Review by Rainyan — DISMISSED** [review]

**Review by nullsystem — CHANGES_REQUESTED** [review]
It fixes spectator and buggy menu opening. However, with team switch while alive is off (default), you can click both Jinrai/NSF buttons, and instead of just closing, it moves forward to class menu, but even more, the class menu shows for your team which kind of makes sense since there's no team switching happening, but instead it should just simply not show it.

**Comment by VantoNortim** [comment]
> It fixes spectator and buggy menu opening. However, with team switch while alive is off (default), you can click both Jinrai/NSF buttons, and instead of just closing, it moves forward to class menu, but even more, the class menu shows for your team which kind of makes sense since there's no team switching happening, but instead it should just simply not show it.

I specifically made it do that, would have assumed that we always want to show class when you change teams even if you are in it already. Next commit will remove this.

File: mp/src/game/client/neo/game_controls/neo_teammenu.cpp [hunk 2]
```diff
@@ -183,69 +183,52 @@ void CNeoTeamMenu::OnCommand(const char *command)
...
-		Assert(false);
-	}
 }
 
 void CNeoTeamMenu::OnKeyCodeReleased(vgui::KeyCode code)
 { // Navigating using the keyboard hack
 	switch (code) {
 	case 92: // F1 - Close the menu
-		ChangeMenu(NULL);
+		CloseMenu();
```
Comment (Rainyan) [inline mp/src/game/client/neo/game_controls/neo_teammenu.cpp:231]: I'm approving since this isn't really related - but since this is going through another round of review currently anyway: this should be refactored as `vgui::KeyCode::KEY_F1` instead of using 92 as a magic number. And instead of setting up a single-case switch, this should be an if condition. But if you can't be bothered to mess with this, we can just merge as-is.

**Review by Rainyan — APPROVED** [review]

**Review by nullsystem — APPROVED** [review]

**Review by nullsystem — APPROVED** [review]

**Review by brysondev — APPROVED** [review]
nt_dimensions_test0001

lgtm

**Comment by nullsystem** [comment]
@VantoNortim Whoops, look like it caused a bug where it just pops up on its own.
