### PR TITLE
Fix grenade bugs

### LINKED ISSUE #708: [BUG] Pressing alt fire once when having a (smoke) grenade or knife in hand causes player to perform an action once
### Build Info

20241012_bc3a767

### Description

After you have equipped a grenade or your knife and press your alt fire button (x by default), your character will trigger the +attack and either slash with the knife or throw your grenade. After that, trying to redo the action by pressing the button will not trigger it again. Primaries/secondaries (besides the weapons that utilize alt fire) do not seem to be affected.

Something to mention is that this cannot be replicated with a detpack.

### To Reproduce

1. Join a server/load a map
2. Select a class that has a throwable/knife
3. After spawning in equip your knife or throwable
4. Press your alt fire key

### Expected behavior

Nothing should happen

### Actual behavior

Your character throws the nade/performs a melee attack. After that, trying to do the same thing results with your character doing nothing

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### LINKED ISSUE #713: Grenades can't be thrown whilst sprinting
### Build Info

v9.0-prealpha

### Description

Grenades and other throwable items should be able to by thrown while sprinting.

### To Reproduce

* Sprint
* Attempt to throw a grenade while sprinting

### Expected behavior

Able to draw back the weapon for a throw, and able to throw the weapon.

### Actual behavior

Throwing is blocked while sprinting.

### Operating System

- [X] Windows
- [X] Linux

### Version/Distro

Windows 10, Linux Mint

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

Related: #466

### PR DESCRIPTION
**Pull request by Rainyan**
## Description
Fix problems with throwable items like grenades.

This PR disables priming throwables with the `+attack2`/"alt fire" button, as that seemed to be happening by mistake.

This also removes the experimental underhanding/lobbing of grenades feature. This was never really properly implemented, and was just remnants from tests years ago. It's not parity, and if we wanted this kind of system in the future, it should probably go through a proper design doc process to be added.

Finally, this fixes the inability to throw grenades/throwables whilst sprinting - parity behaviour is to allow throwing of nades regardless of sprint state.

## Toolchain
- Linux GCC Distro Native [Mint 21.3 + GCC 11.4.0]

## Linked Issues
- Fix #708 
- Fix #713

### CODE REVIEW

File: mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp [hunk 1]
```diff
@@ -465,42 +465,43 @@ void CNEOBaseCombatWeapon::ItemPreFrame(void)
...
+		if (GetNeoWepBits() & NEO_WEP_THROWABLE) {
+			return;
+		}
+		constexpr auto nextAttackDelay = 0.2;
+		m_flNextPrimaryAttack = max(gpGlobals->curtime + nextAttackDelay, m_flNextPrimaryAttack);
+		m_flNextSecondaryAttack = m_flNextPrimaryAttack;
+	};
 
-	if (!m_bLowered && (pOwner->IsSprinting()) && !m_bInReload && !m_bRoundBeingChambered)
+	if (!m_bLowered && !m_bInReload && !m_bRoundBeingChambered && pOwner->IsSprinting())
```
Comment (brysondev) [inline mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp:486]: Interrogative: Are we lowering on ladders still?

If so:
`&& (pOwner->IsSprinting() || bPlayerOnLadder)`

**Review by brysondev — APPROVED** [review]
Just one question but lgtm

File: mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp (hunk 1 above)
Comment (Rainyan) [reply mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp]: Good catch - I had to rebase everything because of merge conflict with master but this should be fixed now

**Review by brysondev — APPROVED** [review]

**Review by AdamTadeusz — APPROVED** [review]
Might be worth opening an issue about grenade throw velocity depending on angle at which it's thrown if we're not pursuing the secondary throw

Edit I guess that would fall under the grenades should behave like og grenades issue
