### PR TITLE
Fix SRS quickswitching

### LINKED ISSUE #1385: SRS quickswitching should be (plugin) parity
### Build Info

v19.0-alpha

### Description

The SRS bolting should be cancellable using the quickswitch mechanic.

In OGNT, the bolting animation can be bypassed entirely by quickswitching away and back to the weapon, allowing for a faster refire time. This is probably not what we want, but instead the [plugin parity](https://github.com/Agiel/nt-srs-limiter) version, which is the typical NT experience players are used to.

In OGNT plugin-parity, the quickswitch can still be used to cancel the bolting animation, but doing so no longer makes you shoot any faster. This is desirable for reasons like quickly exiting the scope, or staying scoped, or just muscle memory and habit.

In NT;RE as of v19.0-alpha, you cannot refire until the bolting animation has been played. Also, if you quickscope, the bolting animation will forcibly pull you away from the scoped-in status against the player's will. This actually makes quickswitching *slower* than not doing so. This doesn't feel good, as the player.

Here's an example clip from the v19.0-alpha playtest from deepfrog, where after performing the quickswitch, he's forcibly pulled out from the scope for the bolting animation, and then has to manually switch to a pistol to continue fighting, which feels really awkward as the controlling player (ideally he should be allowed to remain scoped until ready to shoot again):

https://github.com/user-attachments/assets/5fe59c03-2096-4b1d-a907-a6b75fe826bf

For more video comparisons of OGNT, plugin-parity, and NT;RE, see below.

### To Reproduce

* Shoot the SRS
* Instantly after shooting, switch to a different gun
* Then quickly switch back to the SRS

### Expected behavior

* The bolting animation is cancelled.
* Refire interval is respected.

### Actual behavior

* The bolting animation is not cancelled.
* The bolting animation can interfere with fastest possible refire interval, making the quickswitch *slower* than not doing it.

### Operating System

- [x] Windows
- [ ] Linux

### Version/Distro

11

### Additional context and Screenshots

More examples of the behaviour:

### OG NT
This is the original parity, quickswitching completely unrestricted. Note how I can cancel the bolting animation.

This is not perfect shooting input from me, but just something I recorded quickly. You can shoot somewhat faster than this with good input.

https://github.com/user-attachments/assets/32944833-06f6-4929-8cc4-2aad728974a1

### OG NT, plugin-parity
This is OG NT, but with [Agiel's SRS limiter plugin](https://github.com/Agiel/nt-srs-limiter). The animation can be bypassed, but minimum refire interval is respected. This is probably what we want, since it most closely mirrors the NT experience people are used to.

https://github.com/user-attachments/assets/13f6dc4d-80f7-43ce-8e10-6facc5ae0fda

### NT;RE version v19.0-alpha
This is our current behaviour. Notice how I'm forced into the bolting animation, and cannot continue shooting until the animation is done. It does not feel good as the player.

https://github.com/user-attachments/assets/ded91be0-b4dd-4acc-9de8-a578752d5bfa

### PR DESCRIPTION
**Pull request by Rainyan**
## Description
Fix SRS quickswitching so that we don't cancel the player's scoped state nor block their shoot inputs with the bolting animation.

Note that the quickswitching to block the bolting anim is a separate mechanic from limiting the SRS fire-rate (in plugin-parity), i.e. the player should still not be able to bypass their `m_flNextAttack` fire rate limit as determined by the weapon script's cycle time.

## Toolchain
- Windows MSVC VS2022

## Linked Issues
- fixes #1385
- not addressed/out of scope: #1644

### CODE REVIEW

File: src/game/client/hud_crosshair.cpp [hunk 1]
```diff
@@ -498,8 +498,7 @@ void CHudCrosshair::Paint( void )
 #endif
 		);
 
-		const bool isSRS = pWeapon->GetNeoWepBits() & NEO_WEP_SRS;
-		if (!isSRS || pWeapon->GetRoundChambered())
+		if (!(pWeapon->GetNeoWepBits() & NEO_WEP_SRS))
```
Comment (Agiel) [inline src/game/client/hud_crosshair.cpp]: This change has removed the "dynamic" scope completely from the SRS, whereas the original intention I guess was to temporarily disable it after firing a shot.

Comment (Rainyan) [reply src/game/client/hud_crosshair.cpp]: Oh, whoops. I pushed a commit to fix this.

**Comment by Rainyan** [comment]
> One nit I have is that I feel like OGNT initiates the reload a bit faster when empty, but that might be out of scope (pun intended) for this issue.

I think I'll leave this outside the PR for now.

Another thing I noticed is that we go to the SRS scope instantly, whereas in OGNT there is a delay (eyeballed from 60fps video, it looks like 0.1 seconds) of the viewmodel's scope being raised in front of the camera (presumably to a pos offset defined in the weapon script?), before we actually zoom and render the scoped HUD texture.

Also the OGNT SRS scope FOV change is instant, whereas we do a lerp like with the non-sniper guns, which could change the aim feel especially for quickscoping.
