### PR TITLE
neo_worldpos_marker and neo_npc_targetsystem penetration

### LINKED ISSUE #1372: The team logo above Jeff the tank should not be influenced by HDR
### Build Info

20250824_bebf05c

### Description

The colour of the team logo above Jeff the tank is different when HDR is enabled.

### To Reproduce

1. Enable HDR
2. Load Rogue map and take control of Jeff the tank with the ghost

### Expected behavior

The colour of the team logo above Jeff the tank should not be significantly different when HDR is enabled.

### Actual behavior

_No response_

### Operating System

- [x] Windows
- [ ] Linux

### Version/Distro

10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by DESTROYGIRL**
## Description
- Makes jeff fire bullets using the same method as players, allowing for penetration
- Adds an entity for displaying points of interest on the HUD like ghost caps. Functions similarly to neo_controlpoint from OG and is backwards compatible with maps that used it

## Toolchain
- Windows MSVC VS2022

## Linked Issues
- fixes #1372

### CODE REVIEW

File: src/game/client/neo/ui/neo_hud_worldpos_marker_generic.cpp [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+	}
+	else
+	{
+		const float halfArrowLength = HALF_BASE_TEX_LENGTH * scale;
+		vgui::surface()->DrawSetColor( targetColor );
+		vgui::surface()->DrawTexturedRect(
+			x - halfArrowLength,
+			y - halfArrowLength,
+			x + halfArrowLength,
+			y + halfArrowLength);
```
Comment (Rainyan) [inline src/game/client/neo/ui/neo_hud_worldpos_marker_generic.cpp]: Nit: since we're repeating these lines for both the "if" and the "else", could simplify by removing the else branch entirely, and just executing these lines unconditionally at the end of the function:
```diff
-
-               const float halfArrowLength = HALF_BASE_TEX_LENGTH * scale;
-               vgui::surface()->DrawSetColor(targetColor);
-               vgui::surface()->DrawTexturedRect(
-                       x - halfArrowLength,
-                       y - halfArrowLength,
-                       x + halfArrowLength,
-                       y + halfArrowLength);
-       }
-       else
-       {
-               const float halfArrowLength = HALF_BASE_TEX_LENGTH * scale;
-               vgui::surface()->DrawSetColor( targetColor );
-               vgui::surface()->DrawTexturedRect(
-                       x - halfArrowLength,
-                       y - halfArrowLength,
-                       x + halfArrowLength,
-                       y + halfArrowLength);
        }
+       const float halfArrowLength = HALF_BASE_TEX_LENGTH * scale;
+       vgui::surface()->DrawSetColor(targetColor);
+       vgui::surface()->DrawTexturedRect(
+               x - halfArrowLength,
+               y - halfArrowLength,
+               x + halfArrowLength,
+               y + halfArrowLength);
```

File: src/game/shared/baseentity_shared.cpp [hunk 2]
```diff
@@ -1742,16 +1745,24 @@ void CBaseEntity::FireBullets( const FireBulletsInfo_t &info )
...
 
-	auto neoWeapon = dynamic_cast<CNEOBaseCombatWeapon*>(pNeoAttacker->GetActiveWeapon());
-	Assert(neoWeapon);
+	if ( IsPlayer() )
+	{
+		Assert(pAttacker == this);
+
+		auto pNeoAttacker = dynamic_cast<CNEO_Player*>(this);
+		Assert(pNeoAttacker);
+		pNeoAttacker->m_bIneligibleForLoadoutPick = true;
```
Comment (Rainyan) [inline src/game/shared/baseentity_shared.cpp]: Nit: this could be `assert_cast`, since it will be faster for Release builds but still does the Assert for Debug. Line 1759 on the other hand definitely should remain a `dynamic_cast`, since we do test the nullptr case for it.

File: src/game/shared/neo/neo_worldpos_marker.cpp [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+
+#ifdef GAME_DLL
+void CNEOWorldPosMarkerEnt::Spawn()
+{
+	if ( m_bStartDisabled )
+	{
+		m_bEnabled = false;
+	}
+
+	Assert( ICON_TOTAL == ARRAYSIZE(ICON_PATHS) );
```
Comment (Rainyan) [inline src/game/shared/neo/neo_worldpos_marker.cpp]: Nit: this run-time `Assert` could be changed to compile-time `static_assert` (or alternatively `COMPILE_TIME_ASSERT`, which is a convenience wrapper around `static_assert`)

File: src/game/shared/neo/neo_worldpos_marker.h [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+#else
+	DECLARE_SERVERCLASS();
+#endif
+	DECLARE_DATADESC();
+
+	CNEOWorldPosMarkerEnt();
+	virtual ~CNEOWorldPosMarkerEnt();
+
+#ifdef GAME_DLL
+	virtual void	Spawn();
```
Comment (Rainyan) [inline src/game/shared/neo/neo_worldpos_marker.h]: Nit: would prefer if we specify `override` explicitly

File: src/game/client/neo/ui/neo_hud_worldpos_marker_generic.h [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+private:
+	C_NEOWorldPosMarkerEnt *m_pSource = nullptr;
+	int m_iPosX = 0;
+	int m_iPosY = 0;
+	float m_flDistance = 0.0f;
+	float m_fMarkerScalesStart[4] = { 0.78f, 0.6f, 0.38f, 0.0f };
+	float m_fMarkerScalesCurrent[4] = { 0.78f, 0.6f, 0.38f, 0.0f };
+	wchar_t m_wszMarkerTextUnicode[64 + 1] = {};
+	Vector m_vecMyPos = vec3_origin;
+	vgui::HFont m_hFont = 0UL;
```
Comment (Rainyan) [inline src/game/client/neo/ui/neo_hud_worldpos_marker_generic.h]: Nit: maybe initialize `m_hFont` as `vgui::INVALID_FONT`, instead of using the magic value `0UL`

File: src/game/shared/neo/neo_worldpos_marker.cpp [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+	m_bEnabled = false;
+}
+#else
+void CNEOWorldPosMarkerEnt::PostDataUpdate( DataUpdateType_t updateType )
+{
+	BaseClass::PostDataUpdate( updateType );
+
+	if ( !m_pHUD_WorldPosMarker && updateType == DATA_UPDATE_DATATABLE_CHANGED )
+	{
+		Assert( !m_pHUD_WorldPosMarker );
```
Comment (Rainyan) [inline src/game/shared/neo/neo_worldpos_marker.cpp]: Nit: probably redundant Assert, since the if-condition above already checks for this
