### PR TITLE
Fix players spawning inside eachother, spawnpoint features, small code cleanup

### LINKED ISSUE #1099: Spawn points are missing logic
Missing enable / disable functionality, on spawn output

### PR DESCRIPTION
**Pull request by DESTROYGIRL**
## Description
Title. If a player spawned at a spawn within 128 units of another spawn it would make the other spawn not valid, causing players to spawn inside other players
It might be better to have a more robust way of checking if a player has been spawned at a point but IDK.

## Toolchain

- Windows MSVC VS2022

## Linked Issues

- fixes #1099

### CODE REVIEW

**Review by brysondev — APPROVED** [review]

File: src/game/shared/gamerules.cpp [hunk 1]
```diff
@@ -215,12 +223,22 @@ bool CGameRules::IsSpawnPointValid( CBaseEntity *pSpot, CBasePlayer *pPlayer  )
...
+	}
+#endif
+
 	if ( !pSpot->IsTriggered( pPlayer ) )
 	{
 		return false;
 	}
 
-	for ( CEntitySphereQuery sphere( pSpot->GetAbsOrigin(), 128 ); (ent = sphere.GetCurrentEntity()) != NULL; sphere.NextEntity() )
+	for ( CEntitySphereQuery sphere( pSpot->GetAbsOrigin(), 16 ); (ent = sphere.GetCurrentEntity()) != NULL; sphere.NextEntity() )
```
Comment (AdamTadeusz) [inline src/game/shared/gamerules.cpp:241]: missing #ifdef NEO

Comment (DESTROYGIRL) [reply src/game/shared/gamerules.cpp:241]: Good catch

**Review by brysondev — APPROVED** [review]

**Review by AdamTadeusz — APPROVED** [review]
