### PR TITLE
Refract cloak

### LINKED ISSUE #467: First person cloak effect should match OG NT.
### Build Info

20240629_321f139

### Description

First person cloak effect isn't using the same shader as third person.

### To Reproduce

Press the cloak button

### Expected behavior

The viewmodel should use the "water" shader seen on other players and in OG NT
image

### Actual behavior

The gun goes some sort of blueish transparent.
image

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windors 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### LINKED ISSUE #672: Cloaked people cloaked in thermals
in og, players that are cloaked are drawn with their default material when viewed through thermals
image
in ntre, they appear cloaked
image

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

----> New Material in https://github.com/NeotokyoRebuild/neoAssets/pull/9 Improves cloak visuals <-----
Also hardcoded values in the PR assume the above new material is used.

This PR makes the original refract cloak effect work properly, as well as change the behavior of when player and weapon shadows and models themselves are drawn, to achieve almost the same effect as in the original. Some values like cloak strength increase with distance, rate of strength increase, cloak strength when moving vs standing still and cloak tint still need to be adjusted to get Parity. Also non-active weapons attached to players in this PR are significantly less visible compared to their og counterparts. Need to figure out whether the original behavior was a bug or whether it should be mimicked

Also thank you to @VantoNortim for figuring out how to cloak player weapons drawn with InternalDraw. 

Link to his PR https://github.com/NeotokyoRebuild/neo/pull/665 . #665 as well as https://github.com/NeotokyoRebuild/neo/pull/673 are probably not compatible, I've moved around some of the logic to minimise unnecessary drawing of models and also how they behave with the vision modes. I would close those PRs if people are happy with this one, and am happy to consider @VantoNortim as a co-author of #693 instead

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #467
- fixes #672
- fixes #665

### CODE REVIEW

**Review by brysondev — DISMISSED** [review]

**Review by Rainyan — APPROVED** [review]
LGTM, left some notes but I'd be happy to merge this

**Review by brysondev — DISMISSED** [review]

File: mp/src/game/client/neo/c_neo_player.cpp [hunk 1]
```diff
@@ -443,6 +443,8 @@ C_NEO_Player::C_NEO_Player()
 	m_bLastTickInThermOpticCamo = false;
 	m_bIsAllowedToToggleVision = false;
 
+	m_flTocFactor = 0.15f;
+
```
Comment (Rainyan) [inline mp/src/game/client/neo/c_neo_player.cpp:447]: For some reason GH won't let me comment on this change:

```diff
- m_pPlayerAnimState = CreatePlayerAnimState(this, CreateAnimStateHelpers(this),
-		NEO_ANIMSTATE_LEGANIM_TYPE, NEO_ANIMSTATE_USES_AIMSEQUENCES);
```

but is this related to this PR? Also, if we remove this initialization, it seems `m_pPlayerAnimState` is no longer referred to anywhere, so should we remove it entirely?

**Review by Rainyan — CHANGES_REQUESTED** [review]

File: mp/src/game/client/neo/c_neo_player.cpp (hunk 1 above)
Comment (AdamTadeusz) [reply mp/src/game/client/neo/c_neo_player.cpp:447]: Removing INEOPlayerAnimState was part of Tony Sergi's changes/integrations part 2. I must have forgot to remove this particular value, or some weird git merging

**Review by brysondev — APPROVED** [review]
