### PR TITLE
Reset toggles on death and aim toggle reset when switching weapons and dropping weapons

### LINKED ISSUE #1514: Aim doesn't toggle off automatically when it should when performing various actions
### Build Info

v21.1

### Description

When you have aim toggle on, it does not reset automatically when doing various actions

### To Reproduce

For example: 
1. Aim in 
2. Switch guns

### Expected behavior

Your character should unaim when switching weapons

### Actual behavior

Your character does not unaim after switching weapons

### Operating System

- [x] Windows
- [x] Linux

### Version/Distro

10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### LINKED ISSUE #1516: If you died aimed-in, and the map changes, you'll spawn still aiming in for the next map
### Build Info

v21.1

### Description

Title

### To Reproduce

1. Die whilst aiming in
2. Have the server switch maps

### Expected behavior

You shouldnt be aimed in when you spawn

### Actual behavior

You will spawn aiming in

### Operating System

- [x] Windows
- [x] Linux

### Version/Distro

10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

Resets toggle aim when dropping or switching weapons while maintaining aimed in status when using hold to aim and the weapon switched to supports aiming in, still kinda janky when holding aim button while dropping weapons sometimes

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

-fixes #1514
-fixes #1516

### CODE REVIEW

**Review by VantoNortim — DISMISSED** [review]

**Comment by AdamTadeusz** [comment]
spawning in on a new round if you didn't die is outside the scope of this pr now idk. Networking m_bFirstAliveTick works once and then doesn't work on subsequent rounds someone else can figure it out if they want it fixed quickly

File: src/game/client/neo/c_neo_player.cpp [hunk 1]
```diff
@@ -1656,7 +1660,6 @@ bool C_NEO_Player::ShouldDrawHL2StyleQuickHud(void)
 void C_NEO_Player::Weapon_Drop(C_NEOBaseCombatWeapon *pWeapon)
 {
 	m_bIneligibleForLoadoutPick = true;
-	Weapon_SetZoom(false);
```
Comment (DESTROYGIRL) [inline src/game/client/neo/c_neo_player.cpp:1659]: Removal of this line makes aim stay when dropping weapons, accident? Did you mean to replace it with `IN_AimToggleReset()` or something?

**Review by DESTROYGIRL — APPROVED** [review]

**Review by sunzenshen — APPROVED** [review]
