### PR TITLE
Detpack Fixes

### LINKED ISSUE #906: Detpacks do not function correctly
### Build Info

v11.0

### Description

When throwing detpacks, they sometimes get stuck in midair or hover very close to ground. Also, when throwing them whilst bhopping at high speeds or jumping whilst standing still, they travel way further than they do in OGNT.

### To Reproduce

1. Equip a det
2. Throw it
3. Observe

### Expected behavior

Detpacks land on the ground and travel as fast as in OGNT

### Actual behavior

Detpacks can land and stay above the ground and travel faster than in OGNT

### Operating System

- [x] Windows
- [ ] Linux

### Version/Distro

10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

Might need some (somewhat) empirical testing

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

Detpack projectile does not inherit owner velocity, has settled check checks velocity and if groundentity is set, fixes to the viewmodel when sprinting

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #906

### CODE REVIEW

**Review by Agiel — APPROVED** [review]

File: src/game/server/neo/neo_detpack.cpp [hunk 1]
```diff
@@ -95,7 +95,7 @@ void CNEODeployedDetpack::DelayThink()
 		m_bHasWarnedAI = true;
 	}
 
-	m_hasSettled = CloseEnough(m_lastPos, GetAbsOrigin(), 0.1f);
+	m_hasSettled = GetLocalVelocity().LengthSqr() < 0.5f && GetGroundEntity();
```
Comment (brysondev) [inline src/game/server/neo/neo_detpack.cpp:98]:
```suggestion
	m_hasSettled = (GetLocalVelocity().LengthSqr() < 0.5f) && GetGroundEntity();
```

**Review by brysondev — APPROVED** [review]
