### PR TITLE
Friendly markers - Remove CTargetID, dist/HP in friendly marker, pos

### LINKED ISSUE #427: [BUG] Friendly marker nametag doesn't have distance under it
### Build Info

20240629_321f139

### Description

In OG NT, the friendly marker nametag has distance under it. In NT;RE, no such thing

### To Reproduce

1. Join game
2. Look at teammate
3. No distance

### Expected behavior

Distance under nametag

### Actual behavior

No distance under nametag

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

GNU 10.3.0

### Additional context and Screenshots

In OG NT:
image

In NT;RE:
image

### LINKED ISSUE #428: [BUG] [PARITY] Remove old big nametags
### Build Info

20240629_321f139

### Description

The big nametags need to be gone, they're not in original neotokyo

### To Reproduce

1. Join game
2. Look at teammate directly under the crosshair
3. See big ugly nametag

### Expected behavior

No big ugly nametag, only friendly marker nametag

### Actual behavior

Big ugly nametag

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

GNU 10.3.0

### Additional context and Screenshots

In OG NT (I'm looking directly at him, under the "crosshair"):
image

In NT;RE:
image

Note that for some reason the old nametag also SOMETIMES appears in original neotokyo when testing with bots on a listen server. That SOMETIMES is only for SOME bots, some other bots don't have it when looking at them. Haven't seem them with real players on a real server, however. Weird behavior.

### LINKED ISSUE #429: [FEATURE] HP display near friendly markers
### Description

Have some kind of hp display, whether as text or as some icon, when looking at the friendly marker. Replaces the functionality that old nametags serve in NT;RE, while adding functionality that doesn't exist in OG NT.

### Proposed Solution

As a player, when looking at my teammate's friendly marker anywhere in the map (but more often when they're close to me), I want to see how much HP they have near the friendly marker because it would be useful to know how injured they are, and it'd be easier than matching their nickname with a PFP in the scoreboard and then the PFP with an hp bar in the top hud/the nickname with the HP in the squad hud (if that's gonna be added as a parity feature)

### Alternatives Considered

It could be compared to TF2's custom huds when you hover over a teammate, those often have a cross hp display thing to the left of the nickname. Could also be just a percentage under the nickname, however.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nullsystem**
## Description

* Remove old large text CTargetID
* Introduce distance and HP for friendly markers, shown depending on local vs target player's state
* Position now set to eye's z position, close to OG:NT

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

* fixes #427
* fixes #428
* fixes #429

### CODE REVIEW

**Comment by kassibuss** [comment]
any screenshots?

**Comment by nullsystem** [comment]
@kassibuss 

Player viewing friendly player
2024-07-03T210443_screen

Player viewing friendly player with a ghost
2024-07-03T210852_screen

Spectator viewing a player with ghost and another player without
2024-07-03T210903_screen

**Comment by nullsystem** [comment]
2024-07-03T222342_screen
This is what been agreed upon in the end.

File: mp/src/game/client/hl2mp/hl2mp_hud_target_id.cpp [hunk 1]
```diff
@@ -12,7 +12,7 @@
 
 using namespace vgui;
 
-#ifdef NEO
+#ifndef NEO
 DECLARE_NAMED_HUDELEMENT(CTargetID, TargetID);
 #endif
```
Comment (nullsystem) [inline mp/src/game/client/hl2mp/hl2mp_hud_target_id.cpp:17]: Question for reviewers: Should this be removed entirely as `CTargetID` is not referenced anywhere else or just left as it is?

Comment (Rainyan) [reply mp/src/game/client/hl2mp/hl2mp_hud_target_id.cpp:17]: I wouldn't mind keeping it in the source in case someone wants to cross reference the original implementation for something, but I guess we could drop it from CMakeLists if it's not used anywhere.

File: mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp [hunk 2]
```diff
@@ -107,49 +109,67 @@ void CNEOHud_FriendlyMarker::DrawNeoHudElement()
 void CNEOHud_FriendlyMarker::DrawPlayerForTeam(C_Team* team, const C_NEO_Player* localPlayer) const
 {
 	auto memberCount = team->GetNumPlayers();
+	auto teamColour = GetTeamColour(team->GetTeamNumber());
 	for (int i = 0; i < memberCount; ++i)
 	{
-		auto player = team->GetPlayer(i);
-		auto teamColour = GetTeamColour(team->GetTeamNumber());
+		auto player = dynamic_cast<C_NEO_Player *>(team->GetPlayer(i));
```
Comment (Rainyan) [inline mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp:115]: I think it's a safe assumption that if we ever get a valid `C_BasePlayer*`, it will be castable into a `C_NEO_Player*` (because that should be the only kind of player we have), so this could be `static_cast` for perf.

File: mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp [hunk 3]
```diff
@@ -107,49 +109,67 @@ void CNEOHud_FriendlyMarker::DrawNeoHudElement()
...
+					((!localPlayerAlive || localPlayerSpec) && player->IsCarryingGhost()))
+			{
+				const float flDistance = METERS_PER_INCH * player->GetAbsOrigin().DistTo(localPlayer->GetAbsOrigin());
+				snprintf(textASCII, MAX_MARKER_STRLEN, "%s: %.0fm",
+						 player->IsCarryingGhost() ? "GHOST DISTANCE" : "DISTANCE",
+						 flDistance);
+				DisplayText(textASCII);
+			}
+
+			snprintf(textASCII, MAX_MARKER_STRLEN, "%d%%", player->GetHealth());
```
Comment (Rainyan) [inline mp/src/game/client/neo/ui/neo_hud_friendly_marker.cpp:171]: Perhaps call `V_snprintf`, so we're letting the game engine figure it out instead of relying on platform specific stdio.h directly.

**Review by Rainyan — CHANGES_REQUESTED** [review]

**Review by Rainyan — APPROVED** [review]

**Review by AdamTadeusz — APPROVED** [review]
