### PR TITLE
Dryfire behaviour parity and zr68l sprinting viewmodel fix

### LINKED ISSUE #567: Dry fire behaviour should match OG NT.
### Build Info

0

### Description

After dry firing a gun in OG NT, there's a small delay before the gun is reloaded. Attempting to fire during this time plays the dry fire effect again and the timer is reset. This also means you have a chance to see the dry fire effect on the semi auto guns.

In the current NT;RE version the reload happens as soon as the fire button is released.

### To Reproduce

Fire a gun until it's empty. Observe when the reload happens.

### Expected behavior

There should be a delay.

### Actual behavior

The gun is reloaded immediately.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

3 Seconds of delay after running out of ammunition before automatic reload kicks in, unless you dryfire specifically by pressing the attack key down (instead of holding the attack key down) after you've already run out of ammunition. Also fixes to the srs clicking when holding down the attack key to prevent the bolt from being cycled automatically after running out of ammunition (thought I already fixed this but I guess no?)

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #567

### CODE REVIEW

**Review by Agiel — APPROVED** [review]
I don't like the ZRL hack but the dry firing looks good.

File: mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp [hunk 1]
```diff
@@ -496,7 +496,9 @@ void CNEOBaseCombatWeapon::ProcessAnimationEvents()
 		m_flNextSecondaryAttack = m_flNextPrimaryAttack;
 	};
 
-	if (!m_bLowered && !m_bInReload && !m_bRoundBeingChambered &&
+	// NEO JANK (Adam) Why do we have to bombard the zr68l viewmodel with SendWeaponAnim(ACT_VM_IDLE_LOWERED) during sprint to make it act normally? Breakpoint in SendWeaponAnim isn't triggered by anything else after this animation is sent while sprinting
```
Comment (brysondev) [inline mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp:499]: Animator messed up; should be put in the backlog whenever we get one.

**Review by brysondev — APPROVED** [review]
