### PR TITLE
Fix demoui smoother buttons being unreactive

### LINKED ISSUE #1843: Demo UI smoother should work
### Build Info

v28.1-alpha

### Description

The `demoui` Smoother window which uses the legacy VGUI is currently broken due to some kind of incompatibility with NeoUI.

### To Reproduce

* Press Shift+F2 to open demoui
* Load any demo in the UI
* Pause the demo in the UI
* Press `Smooth...` in the UI
  * The Demo Smoother window should pop up
* In the Demo Smoother window, the `Edge->` or `Process->` buttons

### Expected behavior

The button opens the appropriate dropdown menu.

### Actual behavior

No dropdown menu opens.

### Operating System

- [x] Windows
- [ ] Linux

### Version/Distro

11

### PR DESCRIPTION
**Pull request by Rainyan**
## Description
Fix the `demoui` demo smoother's dropdown buttons in the legacy VGUI not responding to mouse clicks, making the smoother unusable.

If this gets refactored in the future, then https://github.com/NeotokyoRebuild/neo/blob/36087ff754a684355bbf37d9eee9e41e0b8f88a7/src/game/client/mp3player.cpp#L889-L891 should probably also be revisited.

## Toolchain
- Windows MSVC VS2022

## Linked Issues
- fixes #1843 
- related #947
- related #914

### CODE REVIEW

File: src/game/client/cdll_client_int.cpp [hunk 1]
```diff
@@ -1943,6 +1946,106 @@ void CHLClient::DecodeUserCmdFromBuffer( bf_read& buf, int slot )
...
+		parent = child;
+
+		auto* panel = vgui::ipanel()->GetPanel(parent, "BaseUI");
+		if (!panel || !panel->IsVisible())
+		{
+			return;
+		}
+
+		childCount = vgui::ipanel()->GetChildCount(parent);
+		for (i = 0; i < childCount; ++i)
```
Comment (sunzenshen) [inline src/game/client/cdll_client_int.cpp]: Feels a little risky to be reusing the int i iterator in a nested loop like this.  Is it possible that these nested resets of the iterator could use different variables, like i, j, k, ...?  (unless I failed to grok the optimization reason for this reused i)

Then vgui::ipanel()->GetChild(parent, [i,j,k]) could be updated to these new names

Comment (Rainyan) [reply src/game/client/cdll_client_int.cpp]: Whenever we reach line 1989, it will always unconditionally break at line 2044 and therefore `i` cannot tamper with the loop above it (because it must break). The same thing happens at line 2000, where after that loop it'll unconditionally break at line 2042.

I'm reusing `i` because this will run in the `CHLClient::View_Render -> FixupDemoSmoother` which is a hot path that runs every frame (inside the demo viewer context, until we get the successful fix which occurs when the Smoother window is actually opened). For regular runs we bail out at:
```cpp
if (engine->IsPlayingDemo())
{
	FixupDemoSmoother();
}
```
so as to not do all of that vgui looping every frame for regular users.

Although I agree the nesting reads kind of poorly, so I'll see about refactoring it into something clearer.

Comment (sunzenshen) [reply src/game/client/cdll_client_int.cpp]: Makes sense!  I figured there was something I was missing in terms of a hot loop.

Comment (Rainyan) [reply src/game/client/cdll_client_int.cpp]: I did some refactoring to remove the nested loops and make it read a little better.
