### PR TITLE
Backport DM's fixes + spawn menu to master

### LINKED ISSUE #712: TDM not auto-respawning on death
### Build Info

v9.0-prealpha

### Description

Current on TDM, it doesn't automatically respawn you on death especially if killed by an enemy. It may respawn you if you do the "kill"/suicide command. The current DM's PR/branch already has a fix for this. So just a matter of backporting. Could also backport a menu to change class/loadout.

### To Reproduce

To easily reproduce, have two players playing in a server, then:

1. Make sure both have `neo_vote_game_mode 0` to switch to TDM, wait till match starts
2. Player A kill Player B
3. Player B will be sent to spectator mode instead of being spawned in, in which have to manually go back into spawning in.

### Expected behavior

Example "Player B" respawns after being killed.

### Actual behavior

Example "Player B" is sent to spectator/not respawned in.

### Operating System

- [X] Windows
- [X] Linux

### Version/Distro

Windows 10 + Arch Linux

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by nullsystem**
## Description
* Fixes the issue where you do not spawn after being killed by a player
* Fixes where you cannot switch class while you're allowed to switch weapons
* Also add a menu on spawning in to easily switch class

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

* fixes #712

### CODE REVIEW

**Review by brysondev — CHANGES_REQUESTED** [review]

File: mp/src/game/server/neo/neo_player.cpp [hunk 1]
```diff
@@ -135,6 +136,8 @@ void CNEO_Player::RequestSetClass(int newClass)
 	const NeoRoundStatus status = NEORules()->GetRoundStatus();
 	if (IsDead() || sv_neo_can_change_classes_anytime.GetBool() ||
 		(!m_bIneligibleForLoadoutPick && NEORules()->GetRemainingPreRoundFreezeTime(false) > 0) ||
+		(NEORules()->GetGameType() == NEO_GAME_TYPE_TDM && !m_bIneligibleForLoadoutPick &&
+				GetAliveDuration() < neo_sv_dm_max_class_dur.GetFloat()) ||
```
[the remark this answers is not in the document]
Comment (nullsystem) [reply mp/src/game/server/neo/neo_player.cpp:140]: `GetAliveDuration` is in seconds, not milliseconds.

[the remark this answers is not in the document]
Comment (brysondev) [reply mp/src/game/server/neo/neo_player.cpp:140]: So `neo_sv_dm_max_class_dur.GetInt()` and `ConVar neo_sv_dm_max_class_dur("neo_sv_dm_max_class_dur", "10", FCVAR_REPLICATED, "The time in seconds when the player can change class on respawn during deathmatch.", true, 0, true, 60)`?

[the remark this answers is not in the document]
Comment (nullsystem) [reply mp/src/game/server/neo/neo_player.cpp:140]: Don't think it matters much? If someone sets "10.5" then let them. Also this is turning `float < float` to `float < int`.

**Review by brysondev — DISMISSED** [review]

File: mp/src/game/server/neo/neo_player.cpp [hunk 2]
```diff
@@ -123,6 +123,7 @@ ConVar sv_neo_can_change_classes_anytime("sv_neo_can_change_classes_anytime", "0
 	true, 0.0f, true, 1.0f);
 ConVar sv_neo_change_suicide_player("sv_neo_change_suicide_player", "0", FCVAR_REPLICATED, "Kill the player if they change the team and they're alive.", true, 0.0f, true, 1.0f);
 ConVar sv_neo_change_threshold_interval("sv_neo_change_threshold_interval", "0.25", FCVAR_REPLICATED, "The interval threshold limit in seconds before the player is allowed to change team.", true, 0.0f, true, 1000.0f);
```
Comment (AdamTadeusz) [inline mp/src/game/server/neo/neo_player.cpp:125]: I think I just had a stroke trying to read this

File: mp/src/game/server/neo/neo_player.cpp [hunk 3]
```diff
@@ -123,6 +123,7 @@ ConVar sv_neo_can_change_classes_anytime("sv_neo_can_change_classes_anytime", "0
...
+ConVar neo_sv_dm_max_class_dur("neo_sv_dm_max_class_dur", "10", FCVAR_REPLICATED, "The time in seconds when the player can change class on respawn during deathmatch.", true, 0.0f, true, 60.0f);
```
Comment (AdamTadeusz) [inline mp/src/game/server/neo/neo_player.cpp:126]: Having a separate value for class changes and loadout changes is not ideal, but I see why you have it.

File: mp/src/game/server/neo/neo_player.cpp (hunk 2 above)
Comment (nullsystem) [reply mp/src/game/server/neo/neo_player.cpp:125]: Wrong line? Anyway assuming: `neo_sv_dm_max_class_dur` -> `neo_sv_dm_respawn_classpick_duration`?

**Review by AdamTadeusz — APPROVED** [review]
I guess this is useful if someone doesn't have f1-f3 keys, but it doesn't really look great, I would rather they could just rebind the open class and loadout menu instead

File: mp/src/game/server/neo/neo_player.cpp (hunk 2 above)
Comment (AdamTadeusz) [reply mp/src/game/server/neo/neo_player.cpp:125]: correct line, unrelated to this pr

**Comment by AdamTadeusz** [comment]
Seriously why aren't we just using the already provided class and loadout change menu

**Comment by nullsystem** [comment]
> Seriously why aren't we just using the already provided class and loadout change menu

As in having it popup always during spawning in DM/TDM?

**Comment by AdamTadeusz** [comment]
> > Seriously why aren't we just using the already provided class and loadout change menu
> 
> As in having it popup always during spawning in DM/TDM?

yes exactly

**Comment by nullsystem** [comment]
@AdamTadeusz Anonying if I just want to keep on using my current weapon + class

**Comment by AdamTadeusz** [comment]
I think going straight to the loadout screen wouldn't be that annoying, you could see if you unlocked any new weapons. Theres also a button on the loadout screen to change your class if you want to.

**Comment by nullsystem** [comment]
Alright, here it is going straight to loadout menu now

**Review by brysondev — APPROVED** [review]

**Review by AdamTadeusz — APPROVED** [review]
I think this plays great, if there is a want of disabling the selection menu then the old menu could be added, or more likely some checkbox in the redesign perhaps?

**Comment by nullsystem** [comment]
> I think this plays great, if there is a want of disabling the selection menu then the old menu could be added, or more likely some checkbox in the redesign perhaps?

Probably, depends on what people asks for basically
