### PR TITLE
Ghost Uplink, ghost beacons closer to og

### LINKED ISSUE #89: Ghost indicator visual parity with OG:NT

### LINKED ISSUE #430: [BUG] [PARITY] No red popup connecting HUD thing when using ghost during startup delay
### Build Info

20240629_321f139

### Description

In OG NT, there's a red popup connecting HUD thing when the ghost startups in the bottom center of the screen. It's not there in NT;RE, which leads to no obvious tell that it's still starting up

### To Reproduce

1. Pickup ghost
2. See no red popup HUD thing

### Expected behavior

Red popup HUD thing in the bottom center of my screen while the ghost is starting up

### Actual behavior

No red popup HUD thing

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

GNU 10.3.0

### Additional context and Screenshots

In OG NT:

It's animated in game

### LINKED ISSUE #441: Enemy ghost markers do not scale similarly to the current version of NT
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0

### Description

In the current version of NT;RE, the enemy markers you see while holding the ghost scale upwards while closer to an enemy and downwards while away from an enemy. It should be the opposite. Also, the distance markers should be on the side, not at the bottom.

### To Reproduce

1. Pick up ghost
2. Look at the enemy markers

### Expected behavior

Far away enemies have a larger icon and close up enemies have smaller ones. 

### Actual behavior

The enemies close to you have huge markers and far away ones have smaller ones.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

Pictures for comparison, NT;RE at the top and current NT at the bottom. Also, I think the font for the "x M" marker isn't 1:1.
image

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

Adds the ghost uplink hud element to the bottom of the screen, modified ghost beacons to be closer to the original
## Toolchain

- Windows MSVC VS2022

## Linked Issues

- fixes #441
- fixes #430
- fixes #89

### CODE REVIEW

**Comment by AdamTadeusz** [comment]
I thought having the distance to the player on the bottom of the ghost marker looks much better than to the side so didn't cahnge it

**Comment by Agiel** [comment]
Could you post some screenshots to compare?

**Comment by AdamTadeusz** [comment]
Heres a video of the new hud element overlayed onto a recording of the original at host_timescale 0.1 

https://github.com/NeotokyoRebuild/neo/assets/44210793/6760cc05-6471-42ae-a17a-a2c32dc56416

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.h [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+	static constexpr int numTextureStartTimes = 11;
+	int textureOrder[numTextureStartTimes] = {0, 1, 2, 3, 2, 0, 1, 2, 3, 0, 1};
+	float textureStartTimes[numTextureStartTimes] = {0, 0.2, 0.5, 0.6, 1.0, 1.1, 1.4, 1.8, 2.5, 2.7, 3.0};
+	int currentTexture = 0;
+
+	int textureXPos, textureYPos;
+	int m_uplinkTexWidth, m_uplinkTexHeight;
+
+private:
+	CNEOHud_GhostUplinkState(const CNEOHud_GhostUplinkState&other);
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.h:41]: Modern C++ way: `CNEOHud_GhostUplinkState(const CNEOHud_GhostUplinkState &other) = delete;` under public.

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+		return;
+	}
+
+	if (m_flTimeGhostEquip == 0.f) {
+		m_flTimeGhostEquip = gpGlobals->curtime;
+	}
+
+	if (currentTexture < (numTextureStartTimes - 1)) {
+		if ((gpGlobals->curtime - m_flTimeGhostEquip) >= textureStartTimes[currentTexture + 1])
+			currentTexture++;
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp:87]: Should do some sanity checking against `currentTexture >= numUplinkTextures`

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+	constexpr int compassHeightPlusMargins = 30;
+	textureYPos = tall - m_uplinkTexHeight - compassHeightPlusMargins;
+	SetBounds(textureXPos, textureYPos, m_uplinkTexWidth, m_uplinkTexHeight);
+
+	BaseClass::ApplySchemeSettings(pScheme);
+}
+
+void CNEOHud_GhostUplinkState::UpdateStateForNeoHudElementDraw()
+{
+}
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp:65]: Texture change could be utilised in this function instead.

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+
+	surface()->DrawGetTextureSize(m_pUplinkTextures[0], m_uplinkTexWidth, m_uplinkTexHeight);
+
+	SetVisible(true);
+}
+
+void CNEOHud_GhostUplinkState::ApplySchemeSettings(vgui::IScheme* pScheme)
+{
+	vgui::IScheme* scheme = vgui::scheme()->GetIScheme(vgui::scheme()->GetDefaultScheme());
+	Assert(scheme);
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp:49]: Why bypass `pScheme`?

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+
+	int wide, tall;
+	surface()->GetScreenSize(wide, tall);
+	int centerX = wide / 2;
+	int centerY = tall / 2;
+	textureXPos = centerX - (m_uplinkTexWidth / 2);
+	constexpr int compassHeightPlusMargins = 30;
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp:56]: Variable name styling nitpick -> `COMPASS_HEIGHT_PLUS_MARGINS`

File: mp/src/game/client/neo/ui/neo_hud_ghost_beacons.h [hunk 6]
```diff
@@ -6,20 +6,24 @@
...
 
 public:
 	CNEOHud_GhostBeacons(const char *pElementName, vgui::Panel *parent = NULL);
+	virtual void ApplySchemeSettings(vgui::IScheme* pScheme);
 
 	virtual void Paint();
 	void DrawPlayer(const Vector& playerPos) const;
 
+	Vector ghostBeaconOffset = Vector(0, 0, 0);
+	Vector* m_pGhostBeaconOffset = &ghostBeaconOffset;
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_beacons.h:25]: What's with having two variables which one just points to the other when a single `Vector` suffice?

File: mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp [hunk 7]
```diff
@@ -141,38 +141,38 @@ void CNEOHud_GhostBeacons::Paint()
...
-			
-	const Color textColor = Color(220, 180, 180, neo_ghost_beacon_alpha.GetInt());
+{	
 	auto dist = m_pGhost->DistanceToPos(playerPos);	//Move this to some util
+	auto distInMeters = dist * METERS_PER_INCH;
 
+	int posX, posY;
+	if (neo_ghost_beacon_scale_toggle.GetInt() == 0) {
+		constexpr int distanceAtWhichRaiseGhostBeacon = 25;
+		constexpr int maxDistanceGhostBeaconRaised = distanceAtWhichRaiseGhostBeacon * 2;
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_beacons.cpp:151]: Nitpick: Const var should be upper-case styling

**Review by nullsystem — CHANGES_REQUESTED** [review]

File: mp/src/game/client/neo/ui/neo_hud_ghost_beacons.h [hunk 8]
```diff
@@ -32,6 +36,7 @@ class CNEOHud_GhostBeacons : public CNEOHud_ChildElement, public CHudElement, pu
 	bool m_curGhostHolding;
 
 	vgui::HFont m_hFont;
+	Color fontColor = COLOR_WHITE;
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_beacons.h:39]: Unused variable

File: mp/src/game/client/neo/ui/neo_hud_ghost_beacons.h [hunk 9]
```diff
@@ -6,20 +6,24 @@
...
 
-class CNEOHud_GhostBeacons : public CNEOHud_ChildElement, public CHudElement, public vgui::Panel
+class CNEOHud_GhostBeacons : public CNEOHud_ChildElement, public CHudElement, public vgui::EditablePanel
 {
-	DECLARE_CLASS_SIMPLE(CNEOHud_GhostBeacons, Panel);
+	DECLARE_CLASS_SIMPLE(CNEOHud_GhostBeacons, EditablePanel);
 
 public:
 	CNEOHud_GhostBeacons(const char *pElementName, vgui::Panel *parent = NULL);
+	virtual void ApplySchemeSettings(vgui::IScheme* pScheme);
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_beacons.h:19]: Can add `override` to those virtual functions also.

**Review by nullsystem — CHANGES_REQUESTED** [review]

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp (hunk 3 above)
Comment (AdamTadeusz) [reply mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp:65]: Then these need to be member variables
```
static constexpr int numTextureStartTimes = 11;
int textureOrder[numTextureStartTimes] = {0, 1, 2, 3, 2, 0, 1, 2, 3, 0, 1};
float textureStartTimes[numTextureStartTimes] = {0, 0.2, 0.5, 0.6, 1.0, 1.1, 1.4, 1.8, 2.5, 2.7, 3.0};
```

Comment (nullsystem) [reply mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp]: Still not seeing how, instead of going to `DrawNeoHudElement` it can go split into two of those functions?

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp (hunk 2 above)
Comment (AdamTadeusz) [reply mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp]: against ```currentTexture ?= numTextureStartTimes```, currentTexture a better name

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp (hunk 3 above)
Comment (AdamTadeusz) [reply mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp]: I guess I should wrap them together since they're related

Comment (AdamTadeusz) [reply mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp]: But I don't know how so I'l just leave them like this

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.h [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+public:
+	CNEOHud_GhostUplinkState(const char *pElementName, vgui::Panel *parent = NULL);
+	void ApplySchemeSettings(vgui::IScheme* pScheme) override;
+
+	virtual void Paint();
+
+protected:
+	virtual void UpdateStateForNeoHudElementDraw() override;
+	virtual void DrawNeoHudElement() override;
+	virtual ConVar* GetUpdateFrequencyConVar() const;
```
Comment (nullsystem) [inline mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.h:20]: `Paint` and `GetUpdateFrequencyConVar` add `override`

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp (hunk 3 above)
Comment (nullsystem) [reply mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp]: IMO how I'll split it:
* `textureStartTimes` -> local variable in `UpdateStateForNeoHudElementDraw`
* `textureOrder` -> local variable in `DrawNeoHudElement`
* `NUM_TEXTURE_START_TIMES` -> static/anonymous-namespaced var within `neo_hud_ghost_uplink_state.cpp`

**Review by nullsystem — CHANGES_REQUESTED** [review]

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.h (hunk 1 above)
Comment (nullsystem) [reply mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.h:34]: Github made this comment rather hidden if you've didn't notice. But I'll resolve it as it's not too major.

**Review by nullsystem — APPROVED** [review]
Uplink and updated beacon visuals looks good
2024-07-15T175515_screen

File: mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp [hunk 11]
```diff
@@ -0,0 +1,100 @@
...
+
+	SetVisible(true);
+}
+
+void CNEOHud_GhostUplinkState::ApplySchemeSettings(vgui::IScheme* pScheme)
+{
+	int screenWidth, screenHeight;
+	surface()->GetScreenSize(screenWidth, screenHeight);
+	int centerX = screenWidth / 2;
+	int centerY = screenHeight / 2;
```
Comment (Rainyan) [inline mp/src/game/client/neo/ui/neo_hud_ghost_uplink_state.cpp:51]: `centerY` is unused

**Review by Rainyan — CHANGES_REQUESTED** [review]

**Comment by Rainyan** [comment]
Also, graphing the hardcoded values, I'd suspect there's some kind of modified sine wave happening here, where half the period is 1 second long and the whole sequence is 15 seconds. But hardcoding the values seems acceptable for reproducing the original effect.

**Review by Rainyan — APPROVED** [review]
👍

**Review by nullsystem — APPROVED** [review]
