### PR TITLE
AddPoints adds xp instead of frags

### LINKED ISSUE #808: game_score does not function
### Build Info

20241102_14c4282

### Description

The game_score entity (https://developer.valvesoftware.com/wiki/Game_score) does not function as it once did in OGNT. It could be used to modify player XP and team scores of the player who activated it.

### To Reproduce

1. Load nt_rogue_ctg_b3
2. Enable server cheats
3. Type `ent_fire score_negator applyscore` into console

### Expected behavior

The player who entered the command should have +1 XP points visible on the scoreboard

### Actual behavior

The player who entered the command does not have +1 XP points visible on the scoreboard

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 11

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

Steps to reproduce only describe modifying player XP but I have confirmed modifying team points does not work either.

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

Allows changing the players xp with the game_score entity.

AddPointsToTeam functionality remains untouched for TDM game modes for example

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #808

### CODE REVIEW

File: mp/src/game/server/neo/neo_player.cpp [hunk 1]
```diff
@@ -1550,6 +1550,27 @@ void CNEO_Player::StartShowDmgStats(const CTakeDamageInfo* info)
...
+{
+	// Positive score always adds
+	if (score < 0)
+	{
+		if (!bAllowNegativeScore)
+		{
+			if (m_iXP < 0)		// Can't go more negative
+				return;
+
+			if (-score > m_iXP)	// Will this go negative?
```
Comment (brysondev) [inline mp/src/game/server/neo/neo_player.cpp:1563]: Will go negative if suicide no?

**Review by brysondev — APPROVED** [review]
LGTM, but will we make XP negative or frags negative on suicide events?

File: mp/src/game/server/neo/neo_player.cpp (hunk 1 above)
Comment (AdamTadeusz) [reply mp/src/game/server/neo/neo_player.cpp:1563]: Maybe. This replaces player.cpp CBasePlayer::AddPoints for neoplayer but override is returning an error, maybe because of the way CHL2_Player inherits from CBaseMultiplayerPlayer instead of CBasePlayer directly

**Review by brysondev — DISMISSED** [review]

**Comment by DESTROYGIRL** [comment]
> AddPointsToTeam functionality remains untouched for TDM game modes for example

Can you expand on this? As far as my testing goes trying to add team points with the entity does nothing in both CTG and TDM

**Comment by AdamTadeusz** [comment]
> > AddPointsToTeam functionality remains untouched for TDM game modes for example
> 
> Can you expand on this? As far as my testing goes trying to add team points with the entity does nothing in both CTG and TDM

https://github.com/NeotokyoRebuild/neo/issues/808#issuecomment-2490852633 Here is a video, the entity in the map in the video should be set to add points to the callers team instead of to the caller, and thus the white tdm score number goes up

**Comment by DESTROYGIRL** [comment]
> > > AddPointsToTeam functionality remains untouched for TDM game modes for example
> > 
> > 
> > Can you expand on this? As far as my testing goes trying to add team points with the entity does nothing in both CTG and TDM
> 
> [#808 (comment)](https://github.com/NeotokyoRebuild/neo/issues/808#issuecomment-2490852633) Here is a video, the entity in the map in the video should be set to add points to the callers team instead of to the caller, and thus the white tdm score number goes up

Ah I see, I missed that. Sounds good

**Review by brysondev — APPROVED** [review]

**Comment by AdamTadeusz** [comment]
@DESTROYGIRL I was gonna take a look at this pr again soon, are you no longer having problems with it or what happened to your comment

**Comment by DESTROYGIRL** [comment]
> @DESTROYGIRL I was gonna take a look at this pr again soon, are you no longer having problems with it or what happened to your comment

Yeah that was a non-issue. Just retesting now

**Review by DESTROYGIRL — APPROVED** [review]
Works perfect
