### PR TITLE
NeoUI - Add scrollbar to scrollable sections

### LINKED ISSUE #666: NeoUI - Scrollable section missing scrollbar
### Build Info

v8.1-prealpha

### Description

Currently, any scrollable area/section doesn't show a scrollbar and can only use the mouse wheel to scroll.

### To Reproduce

* Scrollable areas but no scrollbars:
    * Create game - map list
    * Settings - Key bindings

### Expected behavior

* A scrollbar visible and interactable on the right-side when a section is scrollable

### Actual behavior

* No scrollbar visble/interactable at all even if a scrollable section

### Operating System

- [X] Windows
- [X] Linux

### Version/Distro

Windows + Linux

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by nullsystem**
## Description
* Current scrollable sections that's immediately noticable:
    * Settings -> Keys
    * Create server/game -> Map list selector
* There might be others like player lists, but they all have the same behavior/style anyway
* Handles mouse drag/click and paint just right-side of defined panel

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

* fixes #666

### CODE REVIEW

File: mp/src/game/client/neo/ui/neo_ui.cpp [hunk 1]
```diff
@@ -311,6 +327,57 @@ void EndSection()
...
+				bAlterOffset = true;
+			}
+			break;
+		case MODE_MOUSERELEASED:
+			g_pCtx->abYMouseDragOffset[g_pCtx->iSection] = false;
+			break;
+		case MODE_MOUSEMOVED:
+			bAlterOffset = g_pCtx->abYMouseDragOffset[g_pCtx->iSection];
+			break;
+		default:
```
Comment (AdamTadeusz) [inline mp/src/game/client/neo/ui/neo_ui.cpp:370]: Nit. I don't think having a default is a requirement in a switch statement. Just an observation I made from reviewing your crosshair PR.

**Review by AdamTadeusz — DISMISSED** [review]

File: mp/src/game/client/neo/ui/neo_ui.cpp (hunk 1 above)
Comment (nullsystem) [reply mp/src/game/client/neo/ui/neo_ui.cpp:370]: While not a requirement, it's fine practice. On GCC (and something similar for MSVC) with `-Wall` on, `-Wswitch` turns on which will complain if an enum case hasn't been handled, where `default: break;` helps rid of that warning. I know this project have switched this warning off but I still will do `default: break;` as a habit as I've done when writing C/C++ switch statements.
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wswitch

File: mp/src/game/client/neo/ui/neo_ui.cpp [hunk 2]
```diff
@@ -311,6 +327,57 @@ void EndSection()
 		}
 	}
 
+	// Scroll bar area painting and mouse interaction (no keyboard as that's handled by active widgets)
+	if (bHasScroll)
+	{
+		const int iYStart = g_pCtx->iYOffset[g_pCtx->iSection];
+		const int iYEnd = iYStart + iRowsInScreen;
+		const float flYPercStart = iYStart / (float)(g_pCtx->iWidget);
```
Comment (Masterkatze) [inline mp/src/game/client/neo/ui/neo_ui.cpp:335]: `static_cast` instead of C-style cast? Same thing below.

File: mp/src/game/client/neo/ui/neo_ui.cpp [hunk 3]
```diff
@@ -279,9 +284,20 @@ void EndSection()
 
 	// Scroll handling
 	const int iRowsInScreen = g_pCtx->dPanel.tall / g_pCtx->iRowTall;
-	if (g_pCtx->eMode == MODE_MOUSEWHEELED && g_pCtx->bMouseInPanel)
+	const bool bHasScroll = (g_pCtx->iPartitionY > iRowsInScreen);
+	vgui::IntRect rectScrollArea = (bHasScroll) ?
```
Comment (Masterkatze) [inline mp/src/game/client/neo/ui/neo_ui.cpp:288]: Sorry for nitpicking, but why parentheses?

Comment (nullsystem) [reply mp/src/game/client/neo/ui/neo_ui.cpp:288]: I generally have a preference on wrapping ternary conditional's condition with parentheses regardless if required or not.

**Review by AdamTadeusz — APPROVED** [review]

**Review by AdamTadeusz — APPROVED** [review]

**Review by brysondev — APPROVED** [review]
