### PR TITLE
Extended Killfeed

### LINKED ISSUE #936: Headshot icon is not aligned with text/icons on high resolutions
### Build Info

v11.2

### Description

Image
When playing at high resolutions, the headshot icons are not aligned properly with the killfeed text and other icons. (Example picture is at 1440p)

### To Reproduce

1. Play game on any resolution higher than 1080p

### Expected behavior

Headshot icons should be aligned with the gun icons and text

### Actual behavior

Headshot icons are not aligned

### Operating System

- [x] Windows
- [x] Linux

### Version/Distro

-

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

Font in =========> https://github.com/NeotokyoRebuild/neoAssets/pull/27 <==========

Adds new events to the killfeed, the ghost capture, vip extraction and rank up. Also converted all textures used in the killfeed to font characters.

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

-fixes #936

### CODE REVIEW

File: src/game/shared/neo/neo_gamerules.cpp [hunk 1]
```diff
@@ -3352,44 +3373,30 @@ void CNEORules::DeathNotice(CBasePlayer* pVictim, const CTakeDamageInfo& info)
 		event->SetInt("userid", pVictim->GetUserID());
 		event->SetInt("attacker", killer_ID);
 		event->SetInt("assists", assists_ID);
-		event->SetString("weapon", killer_weapon_name);
-		event->SetInt("priority", 7);
```
Comment (Masterkatze) [inline src/game/shared/neo/neo_gamerules.cpp:3356]: Is this removed intentionally?

File: game/neo/news.txt [hunk 2]
```diff
@@ -1,3 +1,4 @@
+/blog/2025-02-26	2025-02-26	Pre-Alpha v12.0 Release Note - TF2 SDK update and now 64-bit!
```
Comment (brysondev) [inline game/neo/news.txt:1]: This whole file should be .gitignored no?

File: src/game/client/neo/ui/neo_hud_deathnotice.cpp [hunk 3]
```diff
@@ -0,0 +1,939 @@
...
+constexpr wchar_t GHOST_CAPTURE_TEXT[GHOST_CAPTURE_TEXT_LENGTH] = L" has captured the ";
+
+constexpr int GHOST_CAPTURE_TEXT_2_LENGTH = 19;
+constexpr wchar_t GHOST_CAPTURE_TEXT_2[GHOST_CAPTURE_TEXT_LENGTH] = L" has been captured";
+
+constexpr int VIP_TEXT_LENGTH = 9;
+constexpr wchar_t VIP_TEXT[VIP_TEXT_LENGTH] = L"The VIP ";
+
+constexpr int VIP_EXTRACT_TEXT_LENGTH = 14;
+constexpr wchar_t VIP_EXTRACT_TEXT[VIP_EXTRACT_TEXT_LENGTH] = L"has extracted";
```
Comment (brysondev) [inline src/game/client/neo/ui/neo_hud_deathnotice.cpp:283]:
```suggestion
constexpr wchar_t VIP_EXTRACT_TEXT[VIP_EXTRACT_TEXT_LENGTH] = L" has extracted";
```

File: src/game/client/neo/ui/neo_hud_deathnotice.cpp [hunk 4]
```diff
@@ -0,0 +1,939 @@
...
+
+constexpr int VIP_DEATH_TEXT_LENGTH = 20;
+constexpr wchar_t VIP_DEATH_TEXT[VIP_DEATH_TEXT_LENGTH] = L" has killed the VIP";
+
+constexpr int VIP_DEATH_TEXT_2_LENGTH = 9;
+constexpr wchar_t VIP_DEATH_TEXT_2[VIP_DEATH_TEXT_2_LENGTH] = L"has died";
```
Comment (brysondev) [inline src/game/client/neo/ui/neo_hud_deathnotice.cpp:289]:
```suggestion
constexpr wchar_t VIP_DEATH_TEXT_2[VIP_DEATH_TEXT_2_LENGTH] = L" has died";
```

File: src/game/shared/neo/neo_gamerules.cpp [hunk 5]
```diff
@@ -3107,7 +3132,7 @@ void CNEORules::PlayerKilled(CBasePlayer *pVictim, const CTakeDamageInfo &info)
 	// Suicide or suicide by environment (non-grenade as grenade is likely from a player)
 	if (attacker == victim || (!attacker && !grenade))
 	{
-		victim->m_iXP.GetForModify() -= 1;
+		victim->AddPoints(-1, true);
```
Comment (brysondev) [inline src/game/shared/neo/neo_gamerules.cpp:3135]: NIT/SUG: ConVar for enable/disable negative points on suicide (pub command I'm sure someone might use in the future)

File: src/game/shared/neo/neo_gamerules.cpp [hunk 6]
```diff
@@ -3124,7 +3149,7 @@ void CNEORules::PlayerKilled(CBasePlayer *pVictim, const CTakeDamageInfo &info)
 		// Team kill
 		if (IsTeamplay() && attacker->GetTeamNumber() == victim->GetTeamNumber())
 		{
-			attacker->m_iXP.GetForModify() -= 1;
+			attacker->AddPoints(-1, true);
```
Comment (brysondev) [inline src/game/shared/neo/neo_gamerules.cpp:3152]: ditto

File: src/game/shared/weapon_parse.h [hunk 7]
```diff
@@ -106,6 +106,7 @@ class FileWeaponInfo_t
 #ifdef NEO
 	Vector					vecVmOffset;
 	char					szBulletCharacter[MAX_BULLET_CHARACTER];// character used to display ammunition in current clip
+	char					szDeathIcon[MAX_BULLET_CHARACTER];
```
Comment (brysondev) [inline src/game/shared/weapon_parse.h:109]: NIT/Q: Why are all these variables public and not protected?

**Review by brysondev — CHANGES_REQUESTED** [review]

File: src/game/client/neo/ui/neo_hud_deathnotice.cpp (hunk 3 above)
Comment (AdamTadeusz) [reply src/game/client/neo/ui/neo_hud_deathnotice.cpp:283]: there's no guarantee the three killer, victim and assister players exist, this has been changed on purpose so we can easily control when to print and not to print these extra whitespaces

Comment (AdamTadeusz) [reply src/game/client/neo/ui/neo_hud_deathnotice.cpp:283]: so this can say "The VIP brysondev has extracted", and also "The VIP has extracted" if it cannot find the vip player for whatever reason

File: src/game/shared/neo/neo_gamerules.cpp (hunk 5 above)
Comment (AdamTadeusz) [reply src/game/shared/neo/neo_gamerules.cpp:3135]: what was here previously didn't make that check, and I understand this is a suggestion but I think its appropriate for a separate pr. Without a negative score becoming a rankless dog is impossible

File: src/game/shared/weapon_parse.h (hunk 7 above)
Comment (AdamTadeusz) [reply src/game/shared/weapon_parse.h:109]: I don't know if protecting all these variables is that useful, to answer your question its because I don't care basically. I can add them in if you wish

File: game/neo/news.txt (hunk 2 above)
Comment (AdamTadeusz) [reply game/neo/news.txt:1]: This was done automatically, maybe the fix to master to remove the motoko sprays removed this entry in news.txt? I don't know, adding this to gitignore should be done in a separate pr, I can remove this in a second

File: src/game/shared/weapon_parse.h (hunk 7 above)
Comment (brysondev) [reply src/game/shared/weapon_parse.h:109]: > I don't know if protecting all these variables is that useful, to answer your question its because I don't care basically. I can add them in if you wish

:ebussi:

**Review by brysondev — APPROVED** [review]

**Comment by Agiel** [comment]
Can we have a cvar for the extra info? I think the ghost events are fine, but I'd like to be able to hide the rank ups.

**Review by brysondev — APPROVED** [review]
Oh boy forced playtesting my beloved

**Review by brysondev — APPROVED** [review]

**Review by Masterkatze — APPROVED** [review]
