### PR TITLE
Change ADS toggle from on-release to on-press and sprint related bug fixes

### LINKED ISSUE #276: Sprinting takes precedence over ADS, ADS never prevents you from sprinting
sometimes sprint doesn't come out (I think related to ADS?) - Moffin_dono

### LINKED ISSUE #285: Toggling ADS happens onclick instead of onrelease
Toggle ADS should enable on press of the button, not on release of it (this is how it's like in OGNT) - Wakfu

### LINKED ISSUE #355: Sprint key interrupts aiming for supports
As the support class, whilst being aimed in, pressing the sprint key cancels the aim zoom - even though supports cannot enter into sprint, and hence pressing it should not disrupt their aim.

Likewise, holding the sprint key whilst aiming in causes a buggy jitter where the sprint key is fighting against the zooming motion.

### PR DESCRIPTION
**Pull request by nullsystem**
* Also made sure `neo_aim_hold 1` is not affected negatively by this change
* fixes #285 fixes #276 fixes #355

### CODE REVIEW

**Review by Rainyan — DISMISSED** [review]

File: mp/src/game/server/neo/neo_player.cpp [hunk 1]
```diff
@@ -1096,14 +1097,14 @@ void CNEO_Player::PostThink(void)
 			{
 				static_cast<CWeaponGrenade*>(pNeoWep)->SecondaryAttack();
 			}
-			else if (ClientWantsAimHold(this))
+			else
```
Comment (Agiel) [inline mp/src/game/server/neo/neo_player.cpp:1100]: There's a mismatch between the client and server here. We're not checking if sprint is being held, which means it's possible to start aiming while sprinting.

I'd probably take the time to fix #276 and #355 in the same PR.

**Review by Agiel — CHANGES_REQUESTED** [review]

File: mp/src/game/server/neo/neo_player.cpp (hunk 1 above)
Comment (nullsystem) [reply mp/src/game/server/neo/neo_player.cpp:1097]: Added sprint fixes in PR, although I'm not going to change shared code stuff for the time being as that's more of a wider look at c_neo_player/neo_player split than just this.

**Review by Rainyan — APPROVED** [review]

**Review by Agiel — APPROVED** [review]
