### PR TITLE
Reset crosshair on resets to fix spectator non-matching-to-player xhair

### LINKED ISSUE #1735: Spectating people's crosshairs can show different crosshairs for different people
### Build Info

v26

### Description

Crosshair of the person who's being spectated can look different for each spectator (e.g different color combos or only seeing the default nt crosshair)

### To Reproduce

1. Spectate player(s)

### Expected behavior

Crosshair of the person who is being spectated will look the same for every spectator

### Actual behavior

Crosshair of the person who is being spectated can look different 

### Operating System

- [x] Windows
- [ ] Linux

### Version/Distro

10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by nullsystem**
## Description
This is kind of a guesswork if it'll fix the spectator seeing crosshair on player that it's not the player's actual crosshair, but I'm assuming the state haven't been refreshed properly especialy the timer till next crosshair refresh and maybe on map change and where player index changes it gets stuck with other player's crosshair.

## Toolchain

- Linux GCC Distro Native Arch Linux/GCC 15

## Linked Issues

* fixes #1735

### CODE REVIEW

File: src/game/client/neo/c_neo_player.cpp [hunk 1]
```diff
@@ -1606,6 +1631,13 @@ void C_NEO_Player::Spawn( void )
 			}
 		}
 	}
+
+	// Only do crosshair reset for confirmed local player
+	if (CHudCrosshair *crosshair = GET_HUDELEMENT(CHudCrosshair);
```
Comment (AdamTadeusz) [inline src/game/client/neo/c_neo_player.cpp]: Not a hot path so not really an issue but could check for IsLocalPlayer before searching for this hud element

**Review by AdamTadeusz — APPROVED** [review]
I don't see anything game breaking, but its difficult to see the logic behind why the crosshair is being reset in each of these places, I think some comments would be nice

**Comment by nullsystem** [comment]
@AdamTadeusz Code review changes: https://github.com/NeotokyoRebuild/neo/pull/1877/changes/b06545ed8ac10819a9996d2fb50d2788178e45e8

**Review by AdamTadeusz — APPROVED** [review]
