### PR TITLE
Killer/damager HUD - Various misc fixes

### LINKED ISSUE #1301: Damage dealt not cleared between rounds
How to reproduce
Play a round, damaging and taking damage from some enemy players
Play another round, hiding in a corner of the map without doing either

Expectation:

The taken and dealt numbers on round 2 are both nil

Reality:

The dealt numbers carry over from the previous round

Round 1

Image

Image

Round 2

Image

Image

### PR DESCRIPTION
**Pull request by nullsystem**
## Description
* Fix scores not being cleared properly between rounds
* Readjust widths when there's long names
* Fix suicide kills not being recognized, and further different infos given for suicide kills
* Recognize environmental and `kill` command suicide kills
* Do not display the HUD if there's nothing to display at all
* Hidden convar: `cl_neo_kdinfo_debug_show_local` which can be useful to test name lengths
* More sanity checking

## Toolchain

- Linux GCC Distro Native Gentoo/GCC 14

## Linked Issues

* fixes #1301

### CODE REVIEW

File: src/game/client/clientleafsystem.cpp [hunk 1]
```diff
@@ -1024,7 +1024,7 @@ void CClientLeafSystem::AddShadowToLeaf( int leaf, ClientLeafShadowHandle_t shad
 #ifdef NEO
 		// Engage happily blows past this limit, but it seems to be fine.
 		// Just ignoring this specific case in debug.
-		if (!FStrEq(MapName(), "nt_engage_ctg"))
+		if (!FStrEq(MapName(), "ntre_engage_ctg") && !FStrEq(MapName(), "ntre_skyline_ctg"))
```
Comment (AdamTadeusz) [inline src/game/client/clientleafsystem.cpp]: we also run into this problem almost immediately on rise when spawning on the top spawn

File: src/game/client/neo/c_neo_player.cpp [hunk 2]
```diff
@@ -1460,17 +1460,11 @@ void C_NEO_Player::Spawn( void )
 	m_nVisionLastTick = 0;
 	m_bInLean = NEO_LEAN_NONE;
 
-	for (int i = 0; i < m_rfAttackersScores.Count(); ++i)
+	for (int i = 0; i < MAX_PLAYERS; ++i)
```
Comment (AdamTadeusz) [inline src/game/client/neo/c_neo_player.cpp:1466]: rain would probably say to use ARRAYSIZE (or in this case _ARRAYSIZE), but you have three lists here so not sure, maybe something like this before the loop instead?

image

File: src/game/client/neo/ui/neo_hud_killer_damage_info.cpp [hunk 3]
```diff
@@ -128,15 +129,40 @@ void CNEOHud_KillerDamageInfo::ApplySchemeSettings(vgui::IScheme *pScheme)
...
 	V_memset(&g_neoKDmgInfos, 0, sizeof(CNEOKillerDamageInfos));
-	V_memset(&m_attackersTotals, 0, sizeof(m_attackersTotals));
+	for (int pIdx = 1; pIdx <= gpGlobals->maxClients; ++pIdx)
+	{
+		auto *neoAttacker = dynamic_cast<C_NEO_Player *>(UTIL_PlayerByIndex(pIdx));
+		if (neoAttacker)
+		{
+			for (int i = 0; i < MAX_PLAYERS; ++i)
+			{
+				neoAttacker->m_rfAttackersScores.GetForModify(i) = 0;
```
Comment (AdamTadeusz) [inline src/game/client/neo/ui/neo_hud_killer_damage_info.cpp:140]: _ARRAYSIZE?

File: src/game/client/neo/ui/neo_hud_killer_damage_info.cpp [hunk 4]
```diff
@@ -267,16 +318,38 @@ void CNEOHud_KillerDamageInfo::DrawNeoHudElement()
...
+				{
+					NeoUI::Label(L"Killed by the map");
+				}
+				else if (g_neoKDmgInfos.killerInfo.wszKilledWith[0] == L'\0')
+				{
+					NeoUI::Label(L"Used suicide command");
+				}
+				else
+				{
+					V_swprintf_safe(wszLabel, L"Weapon: %ls", g_neoKDmgInfos.killerInfo.wszKilledWith);
```
Comment (AdamTadeusz) [inline src/game/client/neo/ui/neo_hud_killer_damage_info.cpp:350]: if dead to leeches end up here and wszKilledWith is null

image

File: src/game/server/neo/neo_player.cpp [hunk 5]
```diff
@@ -532,17 +532,11 @@ void CNEO_Player::Spawn(void)
 	m_bAllowGibbing = true;
 	m_bIneligibleForLoadoutPick = false;
 
-	for (int i = 0; i < m_rfAttackersScores.Count(); ++i)
+	for (int i = 0; i < MAX_PLAYERS; ++i)
```
Comment (AdamTadeusz) [inline src/game/server/neo/neo_player.cpp:538]: _ARRAYSIZE?

File: src/game/client/neo/c_neo_player.cpp (hunk 2 above)
Comment (nullsystem) [reply src/game/client/neo/c_neo_player.cpp:1466]: `static_assert` comparing to `MAX_PLAYERS` is fine enough, not going to `_ARRAYSIZE` on the loops because all three variables have to be of `MAX_PLAYERS` anyway.

File: src/game/client/neo/ui/neo_hud_killer_damage_info.cpp (hunk 4 above)
Comment (nullsystem) [reply src/game/client/neo/ui/neo_hud_killer_damage_info.cpp:350]: Leeches doesn't seem to be recognized like an environmental/map kill like the tank, so just gave a more general message for leech kills. Otherwise the rogue's tank now been given a special message for those kills.

File: src/game/client/neo/ui/neo_hud_killer_damage_info.cpp [hunk 6]
```diff
@@ -575,6 +584,15 @@ static void __MsgFunc_DamageInfo(bf_read& msg)
 	else if (killerIdx == NEO_ENVIRON_KILLED)
 	{
 		g_neoKDmgInfos.killerInfo.iEntIndex = NEO_ENVIRON_KILLED;
+		g_neoKDmgInfos.killerInfo.wszKilledWith[0] = L'\0';
+		if (foundKilledBy)
+		{
+			const char *pszMap = IGameSystem::MapName();
```
Comment (AdamTadeusz) [inline src/game/client/neo/ui/neo_hud_killer_damage_info.cpp:590]: Oh hey another unique method for getting the map name.
