### PR TITLE
don't show if spectating

### LINKED ISSUE #935: When spectating someone, the pre-round flavor text is visible
### Build Info

v11.0/v11.2

### Description

When you are in spectator mode, you can see the pre-round flavor text

### To Reproduce

1. Be in spectator
2. Spectate at round start

### Expected behavior

You should only see the health and top hud when spectating

### Actual behavior

You see the flavor text

### Operating System

- [x] Windows
- [x] Linux

### Version/Distro

-

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

Image

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Linked Issues

- fixes #935

### CODE REVIEW

File: src/game/client/neo/ui/neo_hud_startup_sequence.cpp [hunk 1]
```diff
@@ -87,7 +87,7 @@ struct FlavourTextEntry
 
 void CNEOHud_StartupSequence::DrawNeoHudElement()
 {
-	if (!ShouldDraw())
+	if (!ShouldDraw() || IsLocalPlayerSpectator())
```
Comment (brysondev) [inline src/game/client/neo/ui/neo_hud_startup_sequence.cpp:90]:
```suggestion
	if (!ShouldDraw() || IsLocalPlayerSpectator() || engine->IsDemo())
```
Or whatever it was. Might be a useful addition

**Review by brysondev — CHANGES_REQUESTED** [review]

**Comment by AdamTadeusz** [comment]
actually I guess this wouldn't quite work how we want it to

**Comment by AdamTadeusz** [comment]
we're showing all the other hud elements when playing a demo and looking through someones eyes, so I don't think we should hide this particular one

**Review by brysondev — APPROVED** [review]
