### PR TITLE
Spectator xray toggled off on spawn, fixes to how outline is drawn

### LINKED ISSUE #702: Spectator xray can be enabled when dead on a player team, not toggled off when switching away from spectator team or spawning in

### PR DESCRIPTION
**Pull request by AdamTadeusz**
## Description

Re-overrides the material used to draw player glow for every new player drawn, disabled enabling of xray when dead spectating teammates, moves the toggle off of xray vision when changing teams to clientmodeshared

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #702

### CODE REVIEW

**Comment by AdamTadeusz** [comment]
player weapons still aren't outlined when players are cloaked, overriding the material before each attachment is drawn seems to not fix it, don't want to really mess with the base DrawModel functions

File: mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp [hunk 1]
```diff
@@ -1093,22 +1100,29 @@ int CNEOBaseCombatWeapon::DrawModel(int flags)
...
+		modelrender->ForcedMaterialOverride(null);
 	}
 
-	modelrender->ForcedMaterialOverride(null);
 	return ret;
 }
 
 int CNEOBaseCombatWeapon::InternalDrawModel(int flags)
 {
 	int ret = 0;
```
Comment (Rainyan) [inline mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp:1119]: Nitpicking, but could we move this below line 1125 for clarity, since we do a return without using its retval for the added flags check. It's pretty clear currently but if code gets added later it might become nonobvious that it's bypassed by the early BaseClass return otherwise.

File: mp/src/game/client/neo/c_neo_player.cpp [hunk 2]
```diff
@@ -594,6 +594,12 @@ extern ConVar mat_neo_toc_test;
 int C_NEO_Player::DrawModel(int flags)
 {
 	int ret = 0;
+
+	if (flags & STUDIO_IGNORE_NEO_EFFECTS || !(flags & STUDIO_RENDER))
```
Comment (Rainyan) [inline mp/src/game/client/neo/c_neo_player.cpp:598]: Nit: Could we move this `ret` declaration below the early BaseClass return just below here, so after line 602? Just so it's clear we don't actually use it as the retval for that case.

**Review by Rainyan — CHANGES_REQUESTED** [review]
Apologies about the similar note spam, GitHub gets janky when trying to annotate code across wide ranges for the review.

File: mp/src/game/client/clientmode_shared.cpp [hunk 3]
```diff
@@ -814,6 +814,11 @@ int ClientModeShared::HandleSpectatorKeyInput( int down, ButtonCode_t keynum, co
 #ifdef GLOWS_ENABLE
 	else if (down && pszCurrentBinding && Q_strcmp(pszCurrentBinding, "+attack2") == 0)
 	{
+		if (GetLocalPlayerTeam() != TEAM_SPECTATOR)
+		{ // Can't use xray when dead spectating friends
```
[the remark this answers is not in the document]
Comment (AdamTadeusz) [reply mp/src/game/client/clientmode_shared.cpp:818]: We could always just toggle off all glows when spawning in instead. Also once competitive is added check if game is in competitive mode to disable this if not a spectator, also probably some server convar to disable this for players not spectating or outright maybe

[the remark this answers is not in the document]
Comment (AdamTadeusz) [reply mp/src/game/client/clientmode_shared.cpp:818]: to answer your question specifically I hadn't really thought about ghosting, I intended for this to only be available to spectators from the beginning, I considered being able to toggle this when spectating teammates a bug. I can remove this check and remove all client side glow effects when a person spawns into a round, modifying the RemoveGlowEffect function to restore the correct transmit state for each cbasecombatcharacter

[the remark this answers is not in the document]
Comment (AdamTadeusz) [reply mp/src/game/client/clientmode_shared.cpp:818]: Hmm a problem with this is that the client side C_NEO_Player::Spawn is only triggered the first time a person spawns into the map

File: mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp [hunk 4]
```diff
@@ -1093,22 +1100,29 @@ int CNEOBaseCombatWeapon::DrawModel(int flags)
...
 
 	else if (inThermalVision && !pOwner->IsCloaked())
 	{
 		IMaterial* pass = materials->FindMaterial("dev/thermal_third", TEXTURE_GROUP_MODEL);
 		modelrender->ForcedMaterialOverride(pass);
 		ret |= BaseClass::DrawModel(flags);
+		modelrender->ForcedMaterialOverride(null);
 	}
 
-	modelrender->ForcedMaterialOverride(null);
```
[the remark this answers is not in the document]
Comment (AdamTadeusz) [reply mp/src/game/shared/neo/weapons/weapon_neobasecombatweapon.cpp:1105]: xD

**Comment by AdamTadeusz** [comment]
@Rainyan Ok ill stop adding stuff now, the filled in thinner spectator outline can go in a separate pr. It needs a neoAssets pr anyway

**Review by brysondev — APPROVED** [review]
🙈

File: mp/src/game/client/clientmode_shared.cpp [hunk 5]
```diff
@@ -1203,6 +1207,16 @@ void ClientModeShared::FireGameEvent( IGameEvent *event )
 		{
 			// that's me
 			pPlayer->TeamChange( team );
+#ifdef NEO
+			// Switch off Xray when switching teams
+			for (int i = 0; i < MAX_PLAYERS; i++)
```
Comment (Rainyan) [inline mp/src/game/client/clientmode_shared.cpp]: Could we switch the loop condition here to `i < gpGlobals->maxClients` to avoid looping too much for `sv_maxplayers` < 32

File: mp/src/game/client/clientmode_shared.cpp [hunk 6]
```diff
@@ -823,13 +823,12 @@ int ClientModeShared::HandleSpectatorKeyInput( int down, ButtonCode_t keynum, co
 		else
 			engine->ExecuteClientCmd("glow_outline_effect_enable 1");
 
-		for (int i = 0; i < MAX_PLAYERS; i++)
+		bool enabled = glow_outline_effect_enable->GetBool();
+		for (int i = 1; i <= MAX_PLAYERS; i++)
```
Comment (Rainyan) [inline mp/src/game/client/clientmode_shared.cpp:827]: `i <= gpGlobals->maxClients` preferrably

File: mp/src/game/client/clientmode_shared.cpp [hunk 7]
```diff
@@ -823,13 +823,12 @@ int ClientModeShared::HandleSpectatorKeyInput( int down, ButtonCode_t keynum, co
 		else
 			engine->ExecuteClientCmd("glow_outline_effect_enable 1");
```
Comment (Rainyan) [inline mp/src/game/client/clientmode_shared.cpp:824]: You could avoid the redundant hard coding of the cvar & the engine dll indirection with:
```diff
-               if (glow_outline_effect_enable->GetBool())
-                       engine->ExecuteClientCmd("glow_outline_effect_enable 0");
-               else
-                       engine->ExecuteClientCmd("glow_outline_effect_enable 1");
                bool enabled = glow_outline_effect_enable->GetBool();
+               enabled = !enabled;
+               glow_outline_effect_enable->SetValue(enabled);
```

**Review by Rainyan — APPROVED** [review]

**Review by Rainyan — APPROVED** [review]
