### PR TITLE
#1821 Everyone dying on last tick results in a tie

### LINKED ISSUE #1821: NSF always wins if everyone dies at the same time
### Build Info

V28

### Description

When dying at the same tick the round will always be awarded to NSF

### To Reproduce

Last people die at the same time
NSF Wins

### Expected behavior

Its a tie not NSF win

### Actual behavior

_No response_

### Operating System

- [x] Windows
- [ ] Linux

### Version/Distro

10

### Machine's CPU

_No response_

### Machine's GPU

_No response_

### GPU's driver

_No response_

### Build's compiler

_No response_

### Additional context and Screenshots

_No response_

### PR DESCRIPTION
**Pull request by VantoNortim**
## Description
Was tested on the latest build. NSF always won because they were set as winning team last as round winner is decided on the tick people died. Now if everyone is dead it's a tie.

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues
- fixes #1821

### CODE REVIEW

File: src/game/shared/neo/neo_gamerules.cpp [hunk 1]
```diff
@@ -1555,12 +1555,15 @@ void CNEORules::Think(void)
...
-			{
-				if (GetGlobalTeam(team)->GetAliveMembers() == 0)
-				{
-					SetWinningTeam(GetOpposingTeam(team), NEO_VICTORY_TEAM_ELIMINATION, false, true, false, false);
-				}
+			auto jinraiAlive = GetGlobalTeam(TEAM_JINRAI)->GetAliveMembers();
+			auto nsfAlive = GetGlobalTeam(TEAM_NSF)->GetAliveMembers();
+
+			if (jinraiAlive == 0 && nsfAlive == 0) {
+				SetWinningTeam(TEAM_SPECTATOR, NEO_VICTORY_STALEMATE, false, false, true, false);
```
Comment (Agiel) [inline src/game/shared/neo/neo_gamerules.cpp:1562]: bSwitchTeams seems to be passed in inconsistently, but I guess it doesn't matter since it's not used anyway? Something to think about if we revisit half-time later down the line 🤔

Comment (VantoNortim) [reply src/game/shared/neo/neo_gamerules.cpp:1562]: Yeah I went back to look at why it's like that after opening the PR then realised it's not used. Probably should be removed for now even cause if it starts being used it will start breaking stuff lol
